// Generated by packages/qt6/tools/generate_inventory.py; do not edit by hand.
#include "../generated_default_constructors.h"
#include <QtCore/QSet>
#include <algorithm>

#if __has_include(<Qt3DLogic/QFrameAction>)
#include <Qt3DLogic/QFrameAction>
#define KRY_QT6_HAS_QT3DLOGIC_QFrameAction 1
#endif
#if __has_include(<Qt3DLogic/QLogicAspect>)
#include <Qt3DLogic/QLogicAspect>
#define KRY_QT6_HAS_QT3DLOGIC_QLogicAspect 1
#endif

namespace kry_qt6_generated {
bool has_qt3dlogic(const QString &name) {
#ifdef KRY_QT6_HAS_QT3DLOGIC_QFrameAction
    if (name == QLatin1String("QFrameAction") && factory<Qt3DLogic::QFrameAction>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QT3DLOGIC_QLogicAspect
    if (name == QLatin1String("QLogicAspect") && factory<Qt3DLogic::QLogicAspect>() != nullptr) return true;
#endif
    return false;
}
QObject *construct_qt3dlogic(const QString &name, QObject *parent, QString *error) {
#ifdef KRY_QT6_HAS_QT3DLOGIC_QFrameAction
    if (name == QLatin1String("QFrameAction")) { const Factory createClass = factory<Qt3DLogic::QFrameAction>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QT3DLOGIC_QLogicAspect
    if (name == QLatin1String("QLogicAspect")) { const Factory createClass = factory<Qt3DLogic::QLogicAspect>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
    Q_UNUSED(parent);
    Q_UNUSED(error);
    return nullptr;
}
QJsonArray constructors_qt3dlogic() {
    QSet<QString> names;
#ifdef KRY_QT6_HAS_QT3DLOGIC_QFrameAction
    if (factory<Qt3DLogic::QFrameAction>() != nullptr || hasInvokableConstructor<Qt3DLogic::QFrameAction>(QStringLiteral("QFrameAction"))) names.insert(QStringLiteral("QFrameAction"));
#endif
#ifdef KRY_QT6_HAS_QT3DLOGIC_QLogicAspect
    if (factory<Qt3DLogic::QLogicAspect>() != nullptr || hasInvokableConstructor<Qt3DLogic::QLogicAspect>(QStringLiteral("QLogicAspect"))) names.insert(QStringLiteral("QLogicAspect"));
#endif
    QStringList sorted = names.values();
    std::sort(sorted.begin(), sorted.end());
    QJsonArray result;
    for (const QString &name : sorted) result.append(name);
    return result;
}
const QMetaObject *meta_object_qt3dlogic(const QString &name) {
#ifdef KRY_QT6_HAS_QT3DLOGIC_QFrameAction
    if (name == QLatin1String("QFrameAction")) return exactQObjectMetaObject<Qt3DLogic::QFrameAction>(name);
#endif
#ifdef KRY_QT6_HAS_QT3DLOGIC_QLogicAspect
    if (name == QLatin1String("QLogicAspect")) return exactQObjectMetaObject<Qt3DLogic::QLogicAspect>(name);
#endif
    return nullptr;
}
QJsonArray meta_object_names_qt3dlogic() {
    QJsonArray names;
#ifdef KRY_QT6_HAS_QT3DLOGIC_QFrameAction
    if (exactQObjectMetaObject<Qt3DLogic::QFrameAction>(QStringLiteral("QFrameAction")) != nullptr) names.append(QStringLiteral("QFrameAction"));
#endif
#ifdef KRY_QT6_HAS_QT3DLOGIC_QLogicAspect
    if (exactQObjectMetaObject<Qt3DLogic::QLogicAspect>(QStringLiteral("QLogicAspect")) != nullptr) names.append(QStringLiteral("QLogicAspect"));
#endif
    return names;
}
QMetaType value_type_qt3dlogic(const QString &name) {
#ifdef KRY_QT6_HAS_QT3DLOGIC_QFrameAction
    if (name == QLatin1String("QFrameAction")) return gadgetMetaType<Qt3DLogic::QFrameAction>();
#endif
#ifdef KRY_QT6_HAS_QT3DLOGIC_QLogicAspect
    if (name == QLatin1String("QLogicAspect")) return gadgetMetaType<Qt3DLogic::QLogicAspect>();
#endif
    return QMetaType();
}
QJsonArray value_types_qt3dlogic() {
    QJsonArray names;
    if (value_type_qt3dlogic(QStringLiteral("QFrameAction")).isValid()) names.append(QStringLiteral("QFrameAction"));
    if (value_type_qt3dlogic(QStringLiteral("QLogicAspect")).isValid()) names.append(QStringLiteral("QLogicAspect"));
    return names;
}
} // namespace kry_qt6_generated
