// Generated by packages/qt6/tools/generate_inventory.py; do not edit by hand.
#include "../generated_default_constructors.h"
#include <QtCore/QSet>
#include <algorithm>

#if __has_include(<QtSql/QSqlDatabase>)
#include <QtSql/QSqlDatabase>
#define KRY_QT6_HAS_QTSQL_QSqlDatabase 1
#endif
#if __has_include(<QtSql/QSqlDriver>)
#include <QtSql/QSqlDriver>
#define KRY_QT6_HAS_QTSQL_QSqlDriver 1
#endif
#if __has_include(<QtSql/QSqlDriverCreatorBase>)
#include <QtSql/QSqlDriverCreatorBase>
#define KRY_QT6_HAS_QTSQL_QSqlDriverCreatorBase 1
#endif
#if __has_include(<QtSql/QSqlError>)
#include <QtSql/QSqlError>
#define KRY_QT6_HAS_QTSQL_QSqlError 1
#endif
#if __has_include(<QtSql/QSqlField>)
#include <QtSql/QSqlField>
#define KRY_QT6_HAS_QTSQL_QSqlField 1
#endif
#if __has_include(<QtSql/QSqlIndex>)
#include <QtSql/QSqlIndex>
#define KRY_QT6_HAS_QTSQL_QSqlIndex 1
#endif
#if __has_include(<QtSql/QSqlQuery>)
#include <QtSql/QSqlQuery>
#define KRY_QT6_HAS_QTSQL_QSqlQuery 1
#endif
#if __has_include(<QtSql/QSqlQueryModel>)
#include <QtSql/QSqlQueryModel>
#define KRY_QT6_HAS_QTSQL_QSqlQueryModel 1
#endif
#if __has_include(<QtSql/QSqlRecord>)
#include <QtSql/QSqlRecord>
#define KRY_QT6_HAS_QTSQL_QSqlRecord 1
#endif
#if __has_include(<QtSql/QSqlRelation>)
#include <QtSql/QSqlRelation>
#define KRY_QT6_HAS_QTSQL_QSqlRelation 1
#endif
#if __has_include(<QtSql/QSqlRelationalDelegate>)
#include <QtSql/QSqlRelationalDelegate>
#define KRY_QT6_HAS_QTSQL_QSqlRelationalDelegate 1
#endif
#if __has_include(<QtSql/QSqlRelationalTableModel>)
#include <QtSql/QSqlRelationalTableModel>
#define KRY_QT6_HAS_QTSQL_QSqlRelationalTableModel 1
#endif
#if __has_include(<QtSql/QSqlResult>)
#include <QtSql/QSqlResult>
#define KRY_QT6_HAS_QTSQL_QSqlResult 1
#endif
#if __has_include(<QtSql/QSqlTableModel>)
#include <QtSql/QSqlTableModel>
#define KRY_QT6_HAS_QTSQL_QSqlTableModel 1
#endif

namespace kry_qt6_generated {
bool has_qtsql(const QString &name) {
#ifdef KRY_QT6_HAS_QTSQL_QSqlDatabase
    if (name == QLatin1String("QSqlDatabase") && factory<QSqlDatabase>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriver
    if (name == QLatin1String("QSqlDriver") && factory<QSqlDriver>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriverCreatorBase
    if (name == QLatin1String("QSqlDriverCreatorBase") && factory<QSqlDriverCreatorBase>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlError
    if (name == QLatin1String("QSqlError") && factory<QSqlError>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlField
    if (name == QLatin1String("QSqlField") && factory<QSqlField>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlIndex
    if (name == QLatin1String("QSqlIndex") && factory<QSqlIndex>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQuery
    if (name == QLatin1String("QSqlQuery") && factory<QSqlQuery>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQueryModel
    if (name == QLatin1String("QSqlQueryModel") && factory<QSqlQueryModel>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRecord
    if (name == QLatin1String("QSqlRecord") && factory<QSqlRecord>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelation
    if (name == QLatin1String("QSqlRelation") && factory<QSqlRelation>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalDelegate
    if (name == QLatin1String("QSqlRelationalDelegate") && factory<QSqlRelationalDelegate>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalTableModel
    if (name == QLatin1String("QSqlRelationalTableModel") && factory<QSqlRelationalTableModel>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlResult
    if (name == QLatin1String("QSqlResult") && factory<QSqlResult>() != nullptr) return true;
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlTableModel
    if (name == QLatin1String("QSqlTableModel") && factory<QSqlTableModel>() != nullptr) return true;
#endif
    return false;
}
QObject *construct_qtsql(const QString &name, QObject *parent, QString *error) {
#ifdef KRY_QT6_HAS_QTSQL_QSqlDatabase
    if (name == QLatin1String("QSqlDatabase")) { const Factory createClass = factory<QSqlDatabase>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriver
    if (name == QLatin1String("QSqlDriver")) { const Factory createClass = factory<QSqlDriver>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriverCreatorBase
    if (name == QLatin1String("QSqlDriverCreatorBase")) { const Factory createClass = factory<QSqlDriverCreatorBase>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlError
    if (name == QLatin1String("QSqlError")) { const Factory createClass = factory<QSqlError>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlField
    if (name == QLatin1String("QSqlField")) { const Factory createClass = factory<QSqlField>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlIndex
    if (name == QLatin1String("QSqlIndex")) { const Factory createClass = factory<QSqlIndex>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQuery
    if (name == QLatin1String("QSqlQuery")) { const Factory createClass = factory<QSqlQuery>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQueryModel
    if (name == QLatin1String("QSqlQueryModel")) { const Factory createClass = factory<QSqlQueryModel>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRecord
    if (name == QLatin1String("QSqlRecord")) { const Factory createClass = factory<QSqlRecord>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelation
    if (name == QLatin1String("QSqlRelation")) { const Factory createClass = factory<QSqlRelation>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalDelegate
    if (name == QLatin1String("QSqlRelationalDelegate")) { const Factory createClass = factory<QSqlRelationalDelegate>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalTableModel
    if (name == QLatin1String("QSqlRelationalTableModel")) { const Factory createClass = factory<QSqlRelationalTableModel>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlResult
    if (name == QLatin1String("QSqlResult")) { const Factory createClass = factory<QSqlResult>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlTableModel
    if (name == QLatin1String("QSqlTableModel")) { const Factory createClass = factory<QSqlTableModel>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
    Q_UNUSED(parent);
    Q_UNUSED(error);
    return nullptr;
}
QJsonArray constructors_qtsql() {
    QSet<QString> names;
#ifdef KRY_QT6_HAS_QTSQL_QSqlDatabase
    if (factory<QSqlDatabase>() != nullptr || hasInvokableConstructor<QSqlDatabase>(QStringLiteral("QSqlDatabase"))) names.insert(QStringLiteral("QSqlDatabase"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriver
    if (factory<QSqlDriver>() != nullptr || hasInvokableConstructor<QSqlDriver>(QStringLiteral("QSqlDriver"))) names.insert(QStringLiteral("QSqlDriver"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriverCreatorBase
    if (factory<QSqlDriverCreatorBase>() != nullptr || hasInvokableConstructor<QSqlDriverCreatorBase>(QStringLiteral("QSqlDriverCreatorBase"))) names.insert(QStringLiteral("QSqlDriverCreatorBase"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlError
    if (factory<QSqlError>() != nullptr || hasInvokableConstructor<QSqlError>(QStringLiteral("QSqlError"))) names.insert(QStringLiteral("QSqlError"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlField
    if (factory<QSqlField>() != nullptr || hasInvokableConstructor<QSqlField>(QStringLiteral("QSqlField"))) names.insert(QStringLiteral("QSqlField"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlIndex
    if (factory<QSqlIndex>() != nullptr || hasInvokableConstructor<QSqlIndex>(QStringLiteral("QSqlIndex"))) names.insert(QStringLiteral("QSqlIndex"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQuery
    if (factory<QSqlQuery>() != nullptr || hasInvokableConstructor<QSqlQuery>(QStringLiteral("QSqlQuery"))) names.insert(QStringLiteral("QSqlQuery"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQueryModel
    if (factory<QSqlQueryModel>() != nullptr || hasInvokableConstructor<QSqlQueryModel>(QStringLiteral("QSqlQueryModel"))) names.insert(QStringLiteral("QSqlQueryModel"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRecord
    if (factory<QSqlRecord>() != nullptr || hasInvokableConstructor<QSqlRecord>(QStringLiteral("QSqlRecord"))) names.insert(QStringLiteral("QSqlRecord"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelation
    if (factory<QSqlRelation>() != nullptr || hasInvokableConstructor<QSqlRelation>(QStringLiteral("QSqlRelation"))) names.insert(QStringLiteral("QSqlRelation"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalDelegate
    if (factory<QSqlRelationalDelegate>() != nullptr || hasInvokableConstructor<QSqlRelationalDelegate>(QStringLiteral("QSqlRelationalDelegate"))) names.insert(QStringLiteral("QSqlRelationalDelegate"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalTableModel
    if (factory<QSqlRelationalTableModel>() != nullptr || hasInvokableConstructor<QSqlRelationalTableModel>(QStringLiteral("QSqlRelationalTableModel"))) names.insert(QStringLiteral("QSqlRelationalTableModel"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlResult
    if (factory<QSqlResult>() != nullptr || hasInvokableConstructor<QSqlResult>(QStringLiteral("QSqlResult"))) names.insert(QStringLiteral("QSqlResult"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlTableModel
    if (factory<QSqlTableModel>() != nullptr || hasInvokableConstructor<QSqlTableModel>(QStringLiteral("QSqlTableModel"))) names.insert(QStringLiteral("QSqlTableModel"));
#endif
    QStringList sorted = names.values();
    std::sort(sorted.begin(), sorted.end());
    QJsonArray result;
    for (const QString &name : sorted) result.append(name);
    return result;
}
const QMetaObject *meta_object_qtsql(const QString &name) {
#ifdef KRY_QT6_HAS_QTSQL_QSqlDatabase
    if (name == QLatin1String("QSqlDatabase")) return exactQObjectMetaObject<QSqlDatabase>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriver
    if (name == QLatin1String("QSqlDriver")) return exactQObjectMetaObject<QSqlDriver>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriverCreatorBase
    if (name == QLatin1String("QSqlDriverCreatorBase")) return exactQObjectMetaObject<QSqlDriverCreatorBase>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlError
    if (name == QLatin1String("QSqlError")) return exactQObjectMetaObject<QSqlError>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlField
    if (name == QLatin1String("QSqlField")) return exactQObjectMetaObject<QSqlField>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlIndex
    if (name == QLatin1String("QSqlIndex")) return exactQObjectMetaObject<QSqlIndex>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQuery
    if (name == QLatin1String("QSqlQuery")) return exactQObjectMetaObject<QSqlQuery>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQueryModel
    if (name == QLatin1String("QSqlQueryModel")) return exactQObjectMetaObject<QSqlQueryModel>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRecord
    if (name == QLatin1String("QSqlRecord")) return exactQObjectMetaObject<QSqlRecord>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelation
    if (name == QLatin1String("QSqlRelation")) return exactQObjectMetaObject<QSqlRelation>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalDelegate
    if (name == QLatin1String("QSqlRelationalDelegate")) return exactQObjectMetaObject<QSqlRelationalDelegate>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalTableModel
    if (name == QLatin1String("QSqlRelationalTableModel")) return exactQObjectMetaObject<QSqlRelationalTableModel>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlResult
    if (name == QLatin1String("QSqlResult")) return exactQObjectMetaObject<QSqlResult>(name);
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlTableModel
    if (name == QLatin1String("QSqlTableModel")) return exactQObjectMetaObject<QSqlTableModel>(name);
#endif
    return nullptr;
}
QJsonArray meta_object_names_qtsql() {
    QJsonArray names;
#ifdef KRY_QT6_HAS_QTSQL_QSqlDatabase
    if (exactQObjectMetaObject<QSqlDatabase>(QStringLiteral("QSqlDatabase")) != nullptr) names.append(QStringLiteral("QSqlDatabase"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriver
    if (exactQObjectMetaObject<QSqlDriver>(QStringLiteral("QSqlDriver")) != nullptr) names.append(QStringLiteral("QSqlDriver"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriverCreatorBase
    if (exactQObjectMetaObject<QSqlDriverCreatorBase>(QStringLiteral("QSqlDriverCreatorBase")) != nullptr) names.append(QStringLiteral("QSqlDriverCreatorBase"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlError
    if (exactQObjectMetaObject<QSqlError>(QStringLiteral("QSqlError")) != nullptr) names.append(QStringLiteral("QSqlError"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlField
    if (exactQObjectMetaObject<QSqlField>(QStringLiteral("QSqlField")) != nullptr) names.append(QStringLiteral("QSqlField"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlIndex
    if (exactQObjectMetaObject<QSqlIndex>(QStringLiteral("QSqlIndex")) != nullptr) names.append(QStringLiteral("QSqlIndex"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQuery
    if (exactQObjectMetaObject<QSqlQuery>(QStringLiteral("QSqlQuery")) != nullptr) names.append(QStringLiteral("QSqlQuery"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQueryModel
    if (exactQObjectMetaObject<QSqlQueryModel>(QStringLiteral("QSqlQueryModel")) != nullptr) names.append(QStringLiteral("QSqlQueryModel"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRecord
    if (exactQObjectMetaObject<QSqlRecord>(QStringLiteral("QSqlRecord")) != nullptr) names.append(QStringLiteral("QSqlRecord"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelation
    if (exactQObjectMetaObject<QSqlRelation>(QStringLiteral("QSqlRelation")) != nullptr) names.append(QStringLiteral("QSqlRelation"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalDelegate
    if (exactQObjectMetaObject<QSqlRelationalDelegate>(QStringLiteral("QSqlRelationalDelegate")) != nullptr) names.append(QStringLiteral("QSqlRelationalDelegate"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalTableModel
    if (exactQObjectMetaObject<QSqlRelationalTableModel>(QStringLiteral("QSqlRelationalTableModel")) != nullptr) names.append(QStringLiteral("QSqlRelationalTableModel"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlResult
    if (exactQObjectMetaObject<QSqlResult>(QStringLiteral("QSqlResult")) != nullptr) names.append(QStringLiteral("QSqlResult"));
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlTableModel
    if (exactQObjectMetaObject<QSqlTableModel>(QStringLiteral("QSqlTableModel")) != nullptr) names.append(QStringLiteral("QSqlTableModel"));
#endif
    return names;
}
QMetaType value_type_qtsql(const QString &name) {
#ifdef KRY_QT6_HAS_QTSQL_QSqlDatabase
    if (name == QLatin1String("QSqlDatabase")) return gadgetMetaType<QSqlDatabase>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriver
    if (name == QLatin1String("QSqlDriver")) return gadgetMetaType<QSqlDriver>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlDriverCreatorBase
    if (name == QLatin1String("QSqlDriverCreatorBase")) return gadgetMetaType<QSqlDriverCreatorBase>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlError
    if (name == QLatin1String("QSqlError")) return gadgetMetaType<QSqlError>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlField
    if (name == QLatin1String("QSqlField")) return gadgetMetaType<QSqlField>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlIndex
    if (name == QLatin1String("QSqlIndex")) return gadgetMetaType<QSqlIndex>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQuery
    if (name == QLatin1String("QSqlQuery")) return gadgetMetaType<QSqlQuery>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlQueryModel
    if (name == QLatin1String("QSqlQueryModel")) return gadgetMetaType<QSqlQueryModel>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRecord
    if (name == QLatin1String("QSqlRecord")) return gadgetMetaType<QSqlRecord>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelation
    if (name == QLatin1String("QSqlRelation")) return gadgetMetaType<QSqlRelation>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalDelegate
    if (name == QLatin1String("QSqlRelationalDelegate")) return gadgetMetaType<QSqlRelationalDelegate>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlRelationalTableModel
    if (name == QLatin1String("QSqlRelationalTableModel")) return gadgetMetaType<QSqlRelationalTableModel>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlResult
    if (name == QLatin1String("QSqlResult")) return gadgetMetaType<QSqlResult>();
#endif
#ifdef KRY_QT6_HAS_QTSQL_QSqlTableModel
    if (name == QLatin1String("QSqlTableModel")) return gadgetMetaType<QSqlTableModel>();
#endif
    return QMetaType();
}
QJsonArray value_types_qtsql() {
    QJsonArray names;
    if (value_type_qtsql(QStringLiteral("QSqlDatabase")).isValid()) names.append(QStringLiteral("QSqlDatabase"));
    if (value_type_qtsql(QStringLiteral("QSqlDriver")).isValid()) names.append(QStringLiteral("QSqlDriver"));
    if (value_type_qtsql(QStringLiteral("QSqlDriverCreatorBase")).isValid()) names.append(QStringLiteral("QSqlDriverCreatorBase"));
    if (value_type_qtsql(QStringLiteral("QSqlError")).isValid()) names.append(QStringLiteral("QSqlError"));
    if (value_type_qtsql(QStringLiteral("QSqlField")).isValid()) names.append(QStringLiteral("QSqlField"));
    if (value_type_qtsql(QStringLiteral("QSqlIndex")).isValid()) names.append(QStringLiteral("QSqlIndex"));
    if (value_type_qtsql(QStringLiteral("QSqlQuery")).isValid()) names.append(QStringLiteral("QSqlQuery"));
    if (value_type_qtsql(QStringLiteral("QSqlQueryModel")).isValid()) names.append(QStringLiteral("QSqlQueryModel"));
    if (value_type_qtsql(QStringLiteral("QSqlRecord")).isValid()) names.append(QStringLiteral("QSqlRecord"));
    if (value_type_qtsql(QStringLiteral("QSqlRelation")).isValid()) names.append(QStringLiteral("QSqlRelation"));
    if (value_type_qtsql(QStringLiteral("QSqlRelationalDelegate")).isValid()) names.append(QStringLiteral("QSqlRelationalDelegate"));
    if (value_type_qtsql(QStringLiteral("QSqlRelationalTableModel")).isValid()) names.append(QStringLiteral("QSqlRelationalTableModel"));
    if (value_type_qtsql(QStringLiteral("QSqlResult")).isValid()) names.append(QStringLiteral("QSqlResult"));
    if (value_type_qtsql(QStringLiteral("QSqlTableModel")).isValid()) names.append(QStringLiteral("QSqlTableModel"));
    return names;
}
} // namespace kry_qt6_generated
