// Generated by packages/qt6/tools/generate_inventory.py; do not edit by hand.
#include "../generated_default_constructors.h"
#include <QtCore/QSet>
#include <algorithm>

#if __has_include(<QtOpenGLWidgets/QOpenGLWidget>)
#include <QtOpenGLWidgets/QOpenGLWidget>
#define KRY_QT6_HAS_QTOPENGLWIDGETS_QOpenGLWidget 1
#endif

namespace kry_qt6_generated {
bool has_qtopenglwidgets(const QString &name) {
#ifdef KRY_QT6_HAS_QTOPENGLWIDGETS_QOpenGLWidget
    if (name == QLatin1String("QOpenGLWidget") && factory<QOpenGLWidget>() != nullptr) return true;
#endif
    return false;
}
QObject *construct_qtopenglwidgets(const QString &name, QObject *parent, QString *error) {
#ifdef KRY_QT6_HAS_QTOPENGLWIDGETS_QOpenGLWidget
    if (name == QLatin1String("QOpenGLWidget")) { const Factory createClass = factory<QOpenGLWidget>(); if (createClass != nullptr) return createClass(parent, error); }
#endif
    Q_UNUSED(parent);
    Q_UNUSED(error);
    return nullptr;
}
QJsonArray constructors_qtopenglwidgets() {
    QSet<QString> names;
#ifdef KRY_QT6_HAS_QTOPENGLWIDGETS_QOpenGLWidget
    if (factory<QOpenGLWidget>() != nullptr || hasInvokableConstructor<QOpenGLWidget>(QStringLiteral("QOpenGLWidget"))) names.insert(QStringLiteral("QOpenGLWidget"));
#endif
    QStringList sorted = names.values();
    std::sort(sorted.begin(), sorted.end());
    QJsonArray result;
    for (const QString &name : sorted) result.append(name);
    return result;
}
const QMetaObject *meta_object_qtopenglwidgets(const QString &name) {
#ifdef KRY_QT6_HAS_QTOPENGLWIDGETS_QOpenGLWidget
    if (name == QLatin1String("QOpenGLWidget")) return exactQObjectMetaObject<QOpenGLWidget>(name);
#endif
    return nullptr;
}
QJsonArray meta_object_names_qtopenglwidgets() {
    QJsonArray names;
#ifdef KRY_QT6_HAS_QTOPENGLWIDGETS_QOpenGLWidget
    if (exactQObjectMetaObject<QOpenGLWidget>(QStringLiteral("QOpenGLWidget")) != nullptr) names.append(QStringLiteral("QOpenGLWidget"));
#endif
    return names;
}
QMetaType value_type_qtopenglwidgets(const QString &name) {
#ifdef KRY_QT6_HAS_QTOPENGLWIDGETS_QOpenGLWidget
    if (name == QLatin1String("QOpenGLWidget")) return gadgetMetaType<QOpenGLWidget>();
#endif
    return QMetaType();
}
QJsonArray value_types_qtopenglwidgets() {
    QJsonArray names;
    if (value_type_qtopenglwidgets(QStringLiteral("QOpenGLWidget")).isValid()) names.append(QStringLiteral("QOpenGLWidget"));
    return names;
}
} // namespace kry_qt6_generated
