// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QStringList>
#include <type_traits>
#include <utility>

#if __has_include(<QtCore/QCalendarPermission>)
#include <QtCore/QCalendarPermission>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCalendarPermission 1
#endif
#if __has_include(<QtCore/QCameraPermission>)
#include <QtCore/QCameraPermission>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCameraPermission 1
#endif
#if __has_include(<QtCore/QCborStreamReader>)
#include <QtCore/QCborStreamReader>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCborStreamReader 1
#endif
#if __has_include(<QtCore/QCborStreamWriter>)
#include <QtCore/QCborStreamWriter>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCborStreamWriter 1
#endif
#if __has_include(<QtCore/QChildEvent>)
#include <QtCore/QChildEvent>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QChildEvent 1
#endif
#if __has_include(<QtCore/QCollator>)
#include <QtCore/QCollator>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCollator 1
#endif
#if __has_include(<QtCore/QCollatorSortKey>)
#include <QtCore/QCollatorSortKey>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCollatorSortKey 1
#endif
#if __has_include(<QtCore/QCommandLineOption>)
#include <QtCore/QCommandLineOption>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption 1
#endif
#if __has_include(<QtCore/QIODevice>)
#include <QtCore/QIODevice>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QIODEVICE 1
#endif
#if __has_include(<QtCore/QObject>)
#include <QtCore/QObject>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT 1
#endif
#if __has_include(<QtCore/QEvent>)
#include <QtCore/QEvent>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT 1
#endif
#if __has_include(<QtCore/QByteArray>)
#include <QtCore/QByteArray>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY 1
#endif
#if __has_include(<QtCore/QCalendarPermission>)
#include <QtCore/QCalendarPermission>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCALENDARPERMISSION 1
#endif
#if __has_include(<QtCore/QCameraPermission>)
#include <QtCore/QCameraPermission>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCAMERAPERMISSION 1
#endif
#if __has_include(<QtCore/QCollator>)
#include <QtCore/QCollator>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCOLLATOR 1
#endif
#if __has_include(<QtCore/QCollatorSortKey>)
#include <QtCore/QCollatorSortKey>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCOLLATORSORTKEY 1
#endif
#if __has_include(<QtCore/QCommandLineOption>)
#include <QtCore/QCommandLineOption>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCOMMANDLINEOPTION 1
#endif
#if __has_include(<QtCore/QLocale>)
#include <QtCore/QLocale>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QLOCALE 1
#endif

namespace {
template <typename T, typename... Args>
QVariant makeQtValue(Args &&...args) {
    if constexpr (QMetaTypeId2<T>::Defined && std::is_copy_constructible_v<T> && std::is_constructible_v<T, Args...>) return QVariant::fromValue<T>(T(std::forward<Args>(args)...));
    else return {};
}
}

namespace kry_qt6_generated {
bool construct_value_qtcore_1(const QString &moduleName, const QString &className, const QJsonArray &args, QVariant *output, QString *error) {
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCalendarPermission") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCalendarPermission)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QCalendarPermission>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCalendarPermission") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCalendarPermission) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCALENDARPERMISSION)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QCalendarPermission>::Defined && std::is_copy_constructible_v<QCalendarPermission> && std::is_default_constructible_v<QCalendarPermission>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QCalendarPermission>(), error);
            if (!converted0.isValid()) return QVariant();
            const QCalendarPermission arg0 = converted0.value<QCalendarPermission>();
            return makeQtValue<QCalendarPermission>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCameraPermission") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCameraPermission)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QCameraPermission>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCameraPermission") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCameraPermission) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCAMERAPERMISSION)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QCameraPermission>::Defined && std::is_copy_constructible_v<QCameraPermission> && std::is_default_constructible_v<QCameraPermission>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QCameraPermission>(), error);
            if (!converted0.isValid()) return QVariant();
            const QCameraPermission arg0 = converted0.value<QCameraPermission>();
            return makeQtValue<QCameraPermission>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCborStreamReader") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCborStreamReader)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QCborStreamReader>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCborStreamReader") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCborStreamReader) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QByteArray>::Defined && std::is_copy_constructible_v<QByteArray> && std::is_default_constructible_v<QByteArray>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QByteArray>(), error);
            if (!converted0.isValid()) return QVariant();
            const QByteArray arg0 = converted0.value<QByteArray>();
            return makeQtValue<QCborStreamReader>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCborStreamReader) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QIODEVICE)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return QVariant(); }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QIODevice*>(), error);
            if (!converted0.isValid()) return QVariant();
            QIODevice* const arg0 = converted0.value<QIODevice*>();
            return makeQtValue<QCborStreamReader>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCborStreamWriter") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCborStreamWriter) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QIODEVICE)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return QVariant(); }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QIODevice*>(), error);
            if (!converted0.isValid()) return QVariant();
            QIODevice* const arg0 = converted0.value<QIODevice*>();
            return makeQtValue<QCborStreamWriter>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QChildEvent") && args.size() == 2) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QChildEvent) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QEvent::Type>::Defined && std::is_copy_constructible_v<QEvent::Type> && std::is_default_constructible_v<QEvent::Type>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QEvent::Type>(), error);
            if (!converted0.isValid()) return QVariant();
            QEvent::Type arg0 = converted0.value<QEvent::Type>();
            if (args.at(1).isNull()) { *error = QStringLiteral("argument 1 cannot be null"); return QVariant(); }
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QObject*>(), error);
            if (!converted1.isValid()) return QVariant();
            QObject* const arg1 = converted1.value<QObject*>();
            return makeQtValue<QChildEvent>(arg0, arg1);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCollator") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCollator)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QCollator>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCollator") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCollator) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QLOCALE)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QLocale>::Defined && std::is_copy_constructible_v<QLocale> && std::is_default_constructible_v<QLocale>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QLocale>(), error);
            if (!converted0.isValid()) return QVariant();
            const QLocale arg0 = converted0.value<QLocale>();
            return makeQtValue<QCollator>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCollator) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCOLLATOR)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QCollator>::Defined && std::is_copy_constructible_v<QCollator> && std::is_default_constructible_v<QCollator>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QCollator>(), error);
            if (!converted0.isValid()) return QVariant();
            const QCollator arg0 = converted0.value<QCollator>();
            return makeQtValue<QCollator>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCollatorSortKey") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCollatorSortKey) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCOLLATORSORTKEY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QCollatorSortKey>::Defined && std::is_copy_constructible_v<QCollatorSortKey> && std::is_default_constructible_v<QCollatorSortKey>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QCollatorSortKey>(), error);
            if (!converted0.isValid()) return QVariant();
            const QCollatorSortKey arg0 = converted0.value<QCollatorSortKey>();
            return makeQtValue<QCollatorSortKey>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCommandLineOption") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return QVariant(); }
            const QString arg0 = args.at(0).toString();
            return makeQtValue<QCommandLineOption>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!args.at(0).isArray()) { *error = QStringLiteral("argument 0 must be an array"); return QVariant(); }
            QStringList arg0;
            for (const QJsonValue &entry : args.at(0).toArray()) {
                const QVariant converted = kry_qt6_direct::fromJson(entry, QMetaType::fromType<QString>(), error);
                if (!converted.isValid()) return QVariant();
                arg0.append(converted.value<QString>());
            }
            return makeQtValue<QCommandLineOption>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCOMMANDLINEOPTION)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QCommandLineOption>::Defined && std::is_copy_constructible_v<QCommandLineOption> && std::is_default_constructible_v<QCommandLineOption>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QCommandLineOption>(), error);
            if (!converted0.isValid()) return QVariant();
            const QCommandLineOption arg0 = converted0.value<QCommandLineOption>();
            return makeQtValue<QCommandLineOption>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCommandLineOption") && args.size() == 2) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return QVariant(); }
            const QString arg0 = args.at(0).toString();
            if (!(args.at(1).isString())) { *error = QStringLiteral("argument 1 must be a string"); return QVariant(); }
            const QString arg1 = args.at(1).toString();
            return makeQtValue<QCommandLineOption>(arg0, arg1);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!args.at(0).isArray()) { *error = QStringLiteral("argument 0 must be an array"); return QVariant(); }
            QStringList arg0;
            for (const QJsonValue &entry : args.at(0).toArray()) {
                const QVariant converted = kry_qt6_direct::fromJson(entry, QMetaType::fromType<QString>(), error);
                if (!converted.isValid()) return QVariant();
                arg0.append(converted.value<QString>());
            }
            if (!(args.at(1).isString())) { *error = QStringLiteral("argument 1 must be a string"); return QVariant(); }
            const QString arg1 = args.at(1).toString();
            return makeQtValue<QCommandLineOption>(arg0, arg1);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCommandLineOption") && args.size() == 3) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return QVariant(); }
            const QString arg0 = args.at(0).toString();
            if (!(args.at(1).isString())) { *error = QStringLiteral("argument 1 must be a string"); return QVariant(); }
            const QString arg1 = args.at(1).toString();
            if (!(args.at(2).isString())) { *error = QStringLiteral("argument 2 must be a string"); return QVariant(); }
            const QString arg2 = args.at(2).toString();
            return makeQtValue<QCommandLineOption>(arg0, arg1, arg2);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!args.at(0).isArray()) { *error = QStringLiteral("argument 0 must be an array"); return QVariant(); }
            QStringList arg0;
            for (const QJsonValue &entry : args.at(0).toArray()) {
                const QVariant converted = kry_qt6_direct::fromJson(entry, QMetaType::fromType<QString>(), error);
                if (!converted.isValid()) return QVariant();
                arg0.append(converted.value<QString>());
            }
            if (!(args.at(1).isString())) { *error = QStringLiteral("argument 1 must be a string"); return QVariant(); }
            const QString arg1 = args.at(1).toString();
            if (!(args.at(2).isString())) { *error = QStringLiteral("argument 2 must be a string"); return QVariant(); }
            const QString arg2 = args.at(2).toString();
            return makeQtValue<QCommandLineOption>(arg0, arg1, arg2);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtCore")) &&
        className == QLatin1String("QCommandLineOption") && args.size() == 4) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return QVariant(); }
            const QString arg0 = args.at(0).toString();
            if (!(args.at(1).isString())) { *error = QStringLiteral("argument 1 must be a string"); return QVariant(); }
            const QString arg1 = args.at(1).toString();
            if (!(args.at(2).isString())) { *error = QStringLiteral("argument 2 must be a string"); return QVariant(); }
            const QString arg2 = args.at(2).toString();
            if (!(args.at(3).isString())) { *error = QStringLiteral("argument 3 must be a string"); return QVariant(); }
            const QString arg3 = args.at(3).toString();
            return makeQtValue<QCommandLineOption>(arg0, arg1, arg2, arg3);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!args.at(0).isArray()) { *error = QStringLiteral("argument 0 must be an array"); return QVariant(); }
            QStringList arg0;
            for (const QJsonValue &entry : args.at(0).toArray()) {
                const QVariant converted = kry_qt6_direct::fromJson(entry, QMetaType::fromType<QString>(), error);
                if (!converted.isValid()) return QVariant();
                arg0.append(converted.value<QString>());
            }
            if (!(args.at(1).isString())) { *error = QStringLiteral("argument 1 must be a string"); return QVariant(); }
            const QString arg1 = args.at(1).toString();
            if (!(args.at(2).isString())) { *error = QStringLiteral("argument 2 must be a string"); return QVariant(); }
            const QString arg2 = args.at(2).toString();
            if (!(args.at(3).isString())) { *error = QStringLiteral("argument 3 must be a string"); return QVariant(); }
            const QString arg3 = args.at(3).toString();
            return makeQtValue<QCommandLineOption>(arg0, arg1, arg2, arg3);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    return false;
}
QStringList value_constructor_classes_qtcore_1() {
    QStringList result;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCalendarPermission) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCALENDARPERMISSION)
    if ((QMetaTypeId2<QCalendarPermission>::Defined && std::is_copy_constructible_v<QCalendarPermission> && std::is_constructible_v<QCalendarPermission>) || (QMetaTypeId2<QCalendarPermission>::Defined && std::is_copy_constructible_v<QCalendarPermission> && std::is_constructible_v<QCalendarPermission, QCalendarPermission>)) result.append(QStringLiteral("QCalendarPermission"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCameraPermission) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCAMERAPERMISSION)
    if ((QMetaTypeId2<QCameraPermission>::Defined && std::is_copy_constructible_v<QCameraPermission> && std::is_constructible_v<QCameraPermission>) || (QMetaTypeId2<QCameraPermission>::Defined && std::is_copy_constructible_v<QCameraPermission> && std::is_constructible_v<QCameraPermission, QCameraPermission>)) result.append(QStringLiteral("QCameraPermission"));
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QIODEVICE) && defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCborStreamReader) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
    if ((QMetaTypeId2<QCborStreamReader>::Defined && std::is_copy_constructible_v<QCborStreamReader> && std::is_constructible_v<QCborStreamReader>) || (QMetaTypeId2<QCborStreamReader>::Defined && std::is_copy_constructible_v<QCborStreamReader> && std::is_constructible_v<QCborStreamReader, QByteArray>) || (QMetaTypeId2<QCborStreamReader>::Defined && std::is_copy_constructible_v<QCborStreamReader> && std::is_constructible_v<QCborStreamReader, QIODevice*>)) result.append(QStringLiteral("QCborStreamReader"));
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QIODEVICE) && defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCborStreamWriter)
    if ((QMetaTypeId2<QCborStreamWriter>::Defined && std::is_copy_constructible_v<QCborStreamWriter> && std::is_constructible_v<QCborStreamWriter, QIODevice*>)) result.append(QStringLiteral("QCborStreamWriter"));
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT) && defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QChildEvent)
    if ((QMetaTypeId2<QChildEvent>::Defined && std::is_copy_constructible_v<QChildEvent> && std::is_constructible_v<QChildEvent, QEvent::Type, QObject*>)) result.append(QStringLiteral("QChildEvent"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCollator) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCOLLATOR) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QLOCALE)
    if ((QMetaTypeId2<QCollator>::Defined && std::is_copy_constructible_v<QCollator> && std::is_constructible_v<QCollator>) || (QMetaTypeId2<QCollator>::Defined && std::is_copy_constructible_v<QCollator> && std::is_constructible_v<QCollator, QLocale>) || (QMetaTypeId2<QCollator>::Defined && std::is_copy_constructible_v<QCollator> && std::is_constructible_v<QCollator, QCollator>)) result.append(QStringLiteral("QCollator"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCollatorSortKey) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCOLLATORSORTKEY)
    if ((QMetaTypeId2<QCollatorSortKey>::Defined && std::is_copy_constructible_v<QCollatorSortKey> && std::is_constructible_v<QCollatorSortKey, QCollatorSortKey>)) result.append(QStringLiteral("QCollatorSortKey"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTCORE_QCommandLineOption) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QCOMMANDLINEOPTION)
    if ((QMetaTypeId2<QCommandLineOption>::Defined && std::is_copy_constructible_v<QCommandLineOption> && std::is_constructible_v<QCommandLineOption, QString>) || (QMetaTypeId2<QCommandLineOption>::Defined && std::is_copy_constructible_v<QCommandLineOption> && std::is_constructible_v<QCommandLineOption, QStringList>) || (QMetaTypeId2<QCommandLineOption>::Defined && std::is_copy_constructible_v<QCommandLineOption> && std::is_constructible_v<QCommandLineOption, QString, QString, QString, QString>) || (QMetaTypeId2<QCommandLineOption>::Defined && std::is_copy_constructible_v<QCommandLineOption> && std::is_constructible_v<QCommandLineOption, QStringList, QString, QString, QString>) || (QMetaTypeId2<QCommandLineOption>::Defined && std::is_copy_constructible_v<QCommandLineOption> && std::is_constructible_v<QCommandLineOption, QCommandLineOption>)) result.append(QStringLiteral("QCommandLineOption"));
#endif
    return result;
}
} // namespace kry_qt6_generated
