// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QStringList>
#include <type_traits>
#include <utility>

#if __has_include(<QtNetwork/QNetworkAddressEntry>)
#include <QtNetwork/QNetworkAddressEntry>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkAddressEntry 1
#endif
#if __has_include(<QtNetwork/QNetworkCacheMetaData>)
#include <QtNetwork/QNetworkCacheMetaData>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCacheMetaData 1
#endif
#if __has_include(<QtNetwork/QNetworkCookie>)
#include <QtNetwork/QNetworkCookie>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCookie 1
#endif
#if __has_include(<QtNetwork/QNetworkDatagram>)
#include <QtNetwork/QNetworkDatagram>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkDatagram 1
#endif
#if __has_include(<QtNetwork/QNetworkInterface>)
#include <QtNetwork/QNetworkInterface>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkInterface 1
#endif
#if __has_include(<QtNetwork/QNetworkProxy>)
#include <QtNetwork/QNetworkProxy>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxy 1
#endif
#if __has_include(<QtNetwork/QNetworkProxyFactory>)
#include <QtNetwork/QNetworkProxyFactory>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyFactory 1
#endif
#if __has_include(<QtNetwork/QNetworkProxyQuery>)
#include <QtNetwork/QNetworkProxyQuery>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyQuery 1
#endif
#if __has_include(<QtNetwork/QNetworkProxyQuery>)
#include <QtNetwork/QNetworkProxyQuery>
#define KRY_QT6_NATIVE_TYPE_QTNETWORK_QNETWORKPROXYQUERY 1
#endif
#if __has_include(<QtCore/QByteArray>)
#include <QtCore/QByteArray>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY 1
#endif
#if __has_include(<QtCore/QUrl>)
#include <QtCore/QUrl>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QURL 1
#endif
#if __has_include(<QtNetwork/QNetworkAddressEntry>)
#include <QtNetwork/QNetworkAddressEntry>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKADDRESSENTRY 1
#endif
#if __has_include(<QtNetwork/QNetworkCacheMetaData>)
#include <QtNetwork/QNetworkCacheMetaData>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKCACHEMETADATA 1
#endif
#if __has_include(<QtNetwork/QNetworkCookie>)
#include <QtNetwork/QNetworkCookie>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKCOOKIE 1
#endif
#if __has_include(<QtNetwork/QNetworkDatagram>)
#include <QtNetwork/QNetworkDatagram>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKDATAGRAM 1
#endif
#if __has_include(<QtNetwork/QNetworkInterface>)
#include <QtNetwork/QNetworkInterface>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKINTERFACE 1
#endif
#if __has_include(<QtNetwork/QNetworkProxy>)
#include <QtNetwork/QNetworkProxy>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKPROXY 1
#endif
#if __has_include(<QtNetwork/QNetworkProxyQuery>)
#include <QtNetwork/QNetworkProxyQuery>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKPROXYQUERY 1
#endif

namespace {
template <typename T, typename... Args>
QVariant makeQtValue(Args &&...args) {
    if constexpr (QMetaTypeId2<T>::Defined && std::is_copy_constructible_v<T> && std::is_constructible_v<T, Args...>) return QVariant::fromValue<T>(T(std::forward<Args>(args)...));
    else return {};
}
}

namespace kry_qt6_generated {
bool construct_value_qtnetwork_2(const QString &moduleName, const QString &className, const QJsonArray &args, QVariant *output, QString *error) {
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkAddressEntry") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkAddressEntry)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QNetworkAddressEntry>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkAddressEntry") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkAddressEntry) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKADDRESSENTRY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QNetworkAddressEntry>::Defined && std::is_copy_constructible_v<QNetworkAddressEntry> && std::is_default_constructible_v<QNetworkAddressEntry>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNetworkAddressEntry>(), error);
            if (!converted0.isValid()) return QVariant();
            const QNetworkAddressEntry arg0 = converted0.value<QNetworkAddressEntry>();
            return makeQtValue<QNetworkAddressEntry>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkCacheMetaData") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCacheMetaData)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QNetworkCacheMetaData>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkCacheMetaData") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCacheMetaData) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKCACHEMETADATA)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QNetworkCacheMetaData>::Defined && std::is_copy_constructible_v<QNetworkCacheMetaData> && std::is_default_constructible_v<QNetworkCacheMetaData>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNetworkCacheMetaData>(), error);
            if (!converted0.isValid()) return QVariant();
            const QNetworkCacheMetaData arg0 = converted0.value<QNetworkCacheMetaData>();
            return makeQtValue<QNetworkCacheMetaData>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkCookie") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCookie) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QNetworkCookie>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkCookie") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCookie) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QByteArray>::Defined && std::is_copy_constructible_v<QByteArray> && std::is_default_constructible_v<QByteArray>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QByteArray>(), error);
            if (!converted0.isValid()) return QVariant();
            const QByteArray arg0 = converted0.value<QByteArray>();
            return makeQtValue<QNetworkCookie>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCookie) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKCOOKIE)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QNetworkCookie>::Defined && std::is_copy_constructible_v<QNetworkCookie> && std::is_default_constructible_v<QNetworkCookie>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNetworkCookie>(), error);
            if (!converted0.isValid()) return QVariant();
            const QNetworkCookie arg0 = converted0.value<QNetworkCookie>();
            return makeQtValue<QNetworkCookie>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkCookie") && args.size() == 2) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCookie) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QByteArray>::Defined && std::is_copy_constructible_v<QByteArray> && std::is_default_constructible_v<QByteArray>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QByteArray>(), error);
            if (!converted0.isValid()) return QVariant();
            const QByteArray arg0 = converted0.value<QByteArray>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QByteArray>(), error);
            if (!converted1.isValid()) return QVariant();
            const QByteArray arg1 = converted1.value<QByteArray>();
            return makeQtValue<QNetworkCookie>(arg0, arg1);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkDatagram") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkDatagram)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QNetworkDatagram>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkDatagram") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkDatagram) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKDATAGRAM)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QNetworkDatagram>::Defined && std::is_copy_constructible_v<QNetworkDatagram> && std::is_default_constructible_v<QNetworkDatagram>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNetworkDatagram>(), error);
            if (!converted0.isValid()) return QVariant();
            const QNetworkDatagram arg0 = converted0.value<QNetworkDatagram>();
            return makeQtValue<QNetworkDatagram>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkInterface") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkInterface)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QNetworkInterface>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkInterface") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkInterface) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKINTERFACE)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QNetworkInterface>::Defined && std::is_copy_constructible_v<QNetworkInterface> && std::is_default_constructible_v<QNetworkInterface>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNetworkInterface>(), error);
            if (!converted0.isValid()) return QVariant();
            const QNetworkInterface arg0 = converted0.value<QNetworkInterface>();
            return makeQtValue<QNetworkInterface>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkProxy") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxy)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QNetworkProxy>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkProxy") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxy) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKPROXY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QNetworkProxy>::Defined && std::is_copy_constructible_v<QNetworkProxy> && std::is_default_constructible_v<QNetworkProxy>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNetworkProxy>(), error);
            if (!converted0.isValid()) return QVariant();
            const QNetworkProxy arg0 = converted0.value<QNetworkProxy>();
            return makeQtValue<QNetworkProxy>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkProxyFactory") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyFactory)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QNetworkProxyFactory>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkProxyQuery") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyQuery)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QNetworkProxyQuery>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkProxyQuery") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyQuery) && defined(KRY_QT6_NATIVE_TYPE_QTNETWORK_QNETWORKPROXYQUERY) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QURL)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QUrl>::Defined && std::is_copy_constructible_v<QUrl> && std::is_default_constructible_v<QUrl>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QUrl>(), error);
            if (!converted0.isValid()) return QVariant();
            const QUrl arg0 = converted0.value<QUrl>();
            return makeQtValue<QNetworkProxyQuery>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyQuery) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKPROXYQUERY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QNetworkProxyQuery>::Defined && std::is_copy_constructible_v<QNetworkProxyQuery> && std::is_default_constructible_v<QNetworkProxyQuery>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNetworkProxyQuery>(), error);
            if (!converted0.isValid()) return QVariant();
            const QNetworkProxyQuery arg0 = converted0.value<QNetworkProxyQuery>();
            return makeQtValue<QNetworkProxyQuery>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkProxyQuery") && args.size() == 2) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyQuery) && defined(KRY_QT6_NATIVE_TYPE_QTNETWORK_QNETWORKPROXYQUERY) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QURL)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QNetworkProxyQuery::QueryType>::Defined && std::is_copy_constructible_v<QNetworkProxyQuery::QueryType> && std::is_default_constructible_v<QNetworkProxyQuery::QueryType> && QMetaTypeId2<QUrl>::Defined && std::is_copy_constructible_v<QUrl> && std::is_default_constructible_v<QUrl>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QUrl>(), error);
            if (!converted0.isValid()) return QVariant();
            const QUrl arg0 = converted0.value<QUrl>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QNetworkProxyQuery::QueryType>(), error);
            if (!converted1.isValid()) return QVariant();
            QNetworkProxyQuery::QueryType arg1 = converted1.value<QNetworkProxyQuery::QueryType>();
            return makeQtValue<QNetworkProxyQuery>(arg0, arg1);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyQuery) && defined(KRY_QT6_NATIVE_TYPE_QTNETWORK_QNETWORKPROXYQUERY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return QVariant(); }
            const QString arg0 = args.at(0).toString();
            int arg1 = 0;
            if (!args.at(1).isDouble() || !std::isfinite(args.at(1).toDouble()) || std::floor(args.at(1).toDouble()) != args.at(1).toDouble() || args.at(1).toDouble() < std::numeric_limits<int>::min() || args.at(1).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 1 must be a 32-bit integer"); return QVariant(); }
            arg1 = static_cast<int>(args.at(1).toDouble());
            return makeQtValue<QNetworkProxyQuery>(arg0, arg1);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkProxyQuery") && args.size() == 3) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyQuery) && defined(KRY_QT6_NATIVE_TYPE_QTNETWORK_QNETWORKPROXYQUERY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return QVariant(); }
            const QString arg0 = args.at(0).toString();
            int arg1 = 0;
            if (!args.at(1).isDouble() || !std::isfinite(args.at(1).toDouble()) || std::floor(args.at(1).toDouble()) != args.at(1).toDouble() || args.at(1).toDouble() < std::numeric_limits<int>::min() || args.at(1).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 1 must be a 32-bit integer"); return QVariant(); }
            arg1 = static_cast<int>(args.at(1).toDouble());
            if (!(args.at(2).isString())) { *error = QStringLiteral("argument 2 must be a string"); return QVariant(); }
            const QString arg2 = args.at(2).toString();
            return makeQtValue<QNetworkProxyQuery>(arg0, arg1, arg2);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtNetwork")) &&
        className == QLatin1String("QNetworkProxyQuery") && args.size() == 4) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyQuery) && defined(KRY_QT6_NATIVE_TYPE_QTNETWORK_QNETWORKPROXYQUERY)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QNetworkProxyQuery::QueryType>::Defined && std::is_copy_constructible_v<QNetworkProxyQuery::QueryType> && std::is_default_constructible_v<QNetworkProxyQuery::QueryType>) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return QVariant(); }
            const QString arg0 = args.at(0).toString();
            int arg1 = 0;
            if (!args.at(1).isDouble() || !std::isfinite(args.at(1).toDouble()) || std::floor(args.at(1).toDouble()) != args.at(1).toDouble() || args.at(1).toDouble() < std::numeric_limits<int>::min() || args.at(1).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 1 must be a 32-bit integer"); return QVariant(); }
            arg1 = static_cast<int>(args.at(1).toDouble());
            if (!(args.at(2).isString())) { *error = QStringLiteral("argument 2 must be a string"); return QVariant(); }
            const QString arg2 = args.at(2).toString();
            const QVariant converted3 = kry_qt6_direct::fromJson(args.at(3), QMetaType::fromType<QNetworkProxyQuery::QueryType>(), error);
            if (!converted3.isValid()) return QVariant();
            QNetworkProxyQuery::QueryType arg3 = converted3.value<QNetworkProxyQuery::QueryType>();
            return makeQtValue<QNetworkProxyQuery>(arg0, arg1, arg2, arg3);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    return false;
}
QStringList value_constructor_classes_qtnetwork_2() {
    QStringList result;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkAddressEntry) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKADDRESSENTRY)
    if ((QMetaTypeId2<QNetworkAddressEntry>::Defined && std::is_copy_constructible_v<QNetworkAddressEntry> && std::is_constructible_v<QNetworkAddressEntry>) || (QMetaTypeId2<QNetworkAddressEntry>::Defined && std::is_copy_constructible_v<QNetworkAddressEntry> && std::is_constructible_v<QNetworkAddressEntry, QNetworkAddressEntry>)) result.append(QStringLiteral("QNetworkAddressEntry"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCacheMetaData) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKCACHEMETADATA)
    if ((QMetaTypeId2<QNetworkCacheMetaData>::Defined && std::is_copy_constructible_v<QNetworkCacheMetaData> && std::is_constructible_v<QNetworkCacheMetaData>) || (QMetaTypeId2<QNetworkCacheMetaData>::Defined && std::is_copy_constructible_v<QNetworkCacheMetaData> && std::is_constructible_v<QNetworkCacheMetaData, QNetworkCacheMetaData>)) result.append(QStringLiteral("QNetworkCacheMetaData"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkCookie) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKCOOKIE)
    if ((QMetaTypeId2<QNetworkCookie>::Defined && std::is_copy_constructible_v<QNetworkCookie> && std::is_constructible_v<QNetworkCookie, QByteArray, QByteArray>) || (QMetaTypeId2<QNetworkCookie>::Defined && std::is_copy_constructible_v<QNetworkCookie> && std::is_constructible_v<QNetworkCookie, QNetworkCookie>)) result.append(QStringLiteral("QNetworkCookie"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkDatagram) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKDATAGRAM)
    if ((QMetaTypeId2<QNetworkDatagram>::Defined && std::is_copy_constructible_v<QNetworkDatagram> && std::is_constructible_v<QNetworkDatagram>) || (QMetaTypeId2<QNetworkDatagram>::Defined && std::is_copy_constructible_v<QNetworkDatagram> && std::is_constructible_v<QNetworkDatagram, QNetworkDatagram>)) result.append(QStringLiteral("QNetworkDatagram"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkInterface) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKINTERFACE)
    if ((QMetaTypeId2<QNetworkInterface>::Defined && std::is_copy_constructible_v<QNetworkInterface> && std::is_constructible_v<QNetworkInterface>) || (QMetaTypeId2<QNetworkInterface>::Defined && std::is_copy_constructible_v<QNetworkInterface> && std::is_constructible_v<QNetworkInterface, QNetworkInterface>)) result.append(QStringLiteral("QNetworkInterface"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxy) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKPROXY)
    if ((QMetaTypeId2<QNetworkProxy>::Defined && std::is_copy_constructible_v<QNetworkProxy> && std::is_constructible_v<QNetworkProxy>) || (QMetaTypeId2<QNetworkProxy>::Defined && std::is_copy_constructible_v<QNetworkProxy> && std::is_constructible_v<QNetworkProxy, QNetworkProxy>)) result.append(QStringLiteral("QNetworkProxy"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyFactory)
    if ((QMetaTypeId2<QNetworkProxyFactory>::Defined && std::is_copy_constructible_v<QNetworkProxyFactory> && std::is_constructible_v<QNetworkProxyFactory>)) result.append(QStringLiteral("QNetworkProxyFactory"));
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTNETWORK_QNETWORKPROXYQUERY) && defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTNETWORK_QNetworkProxyQuery) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QURL) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNETWORK_QNETWORKPROXYQUERY)
    if ((QMetaTypeId2<QNetworkProxyQuery>::Defined && std::is_copy_constructible_v<QNetworkProxyQuery> && std::is_constructible_v<QNetworkProxyQuery>) || (QMetaTypeId2<QNetworkProxyQuery>::Defined && std::is_copy_constructible_v<QNetworkProxyQuery> && std::is_constructible_v<QNetworkProxyQuery, QUrl, QNetworkProxyQuery::QueryType>) || (QMetaTypeId2<QNetworkProxyQuery>::Defined && std::is_copy_constructible_v<QNetworkProxyQuery> && std::is_constructible_v<QNetworkProxyQuery, QString, int, QString, QNetworkProxyQuery::QueryType>) || (QMetaTypeId2<QNetworkProxyQuery>::Defined && std::is_copy_constructible_v<QNetworkProxyQuery> && std::is_constructible_v<QNetworkProxyQuery, QNetworkProxyQuery>)) result.append(QStringLiteral("QNetworkProxyQuery"));
#endif
    return result;
}
} // namespace kry_qt6_generated
