// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QStringList>
#include <type_traits>
#include <utility>

#if __has_include(<QtSvg/QSvgGenerator>)
#include <QtSvg/QSvgGenerator>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTSVG_QSvgGenerator 1
#endif
#if __has_include(<QtSvg/QSvgGenerator>)
#include <QtSvg/QSvgGenerator>
#define KRY_QT6_NATIVE_TYPE_QTSVG_QSVGGENERATOR 1
#endif

namespace {
template <typename T, typename... Args>
QVariant makeQtValue(Args &&...args) {
    if constexpr (QMetaTypeId2<T>::Defined && std::is_copy_constructible_v<T> && std::is_constructible_v<T, Args...>) return QVariant::fromValue<T>(T(std::forward<Args>(args)...));
    else return {};
}
}

namespace kry_qt6_generated {
bool construct_value_qtsvg_0(const QString &moduleName, const QString &className, const QJsonArray &args, QVariant *output, QString *error) {
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtSvg")) &&
        className == QLatin1String("QSvgGenerator") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTSVG_QSvgGenerator)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QSvgGenerator>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtSvg")) &&
        className == QLatin1String("QSvgGenerator") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTSVG_QSvgGenerator) && defined(KRY_QT6_NATIVE_TYPE_QTSVG_QSVGGENERATOR)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QSvgGenerator::SvgVersion>::Defined && std::is_copy_constructible_v<QSvgGenerator::SvgVersion> && std::is_default_constructible_v<QSvgGenerator::SvgVersion>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QSvgGenerator::SvgVersion>(), error);
            if (!converted0.isValid()) return QVariant();
            QSvgGenerator::SvgVersion arg0 = converted0.value<QSvgGenerator::SvgVersion>();
            return makeQtValue<QSvgGenerator>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    return false;
}
QStringList value_constructor_classes_qtsvg_0() {
    QStringList result;
#if defined(KRY_QT6_NATIVE_TYPE_QTSVG_QSVGGENERATOR) && defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTSVG_QSvgGenerator)
    if ((QMetaTypeId2<QSvgGenerator>::Defined && std::is_copy_constructible_v<QSvgGenerator> && std::is_constructible_v<QSvgGenerator>) || (QMetaTypeId2<QSvgGenerator>::Defined && std::is_copy_constructible_v<QSvgGenerator> && std::is_constructible_v<QSvgGenerator, QSvgGenerator::SvgVersion>)) result.append(QStringLiteral("QSvgGenerator"));
#endif
    return result;
}
} // namespace kry_qt6_generated
