// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QStringList>
#include <type_traits>
#include <utility>

#if __has_include(<QtGui/QFontMetricsF>)
#include <QtGui/QFontMetricsF>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QFontMetricsF 1
#endif
#if __has_include(<QtGui/QFontVariableAxis>)
#include <QtGui/QFontVariableAxis>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QFontVariableAxis 1
#endif
#if __has_include(<QtGui/QGlyphRun>)
#include <QtGui/QGlyphRun>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QGlyphRun 1
#endif
#if __has_include(<QtGui/QGradient>)
#include <QtGui/QGradient>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QGradient 1
#endif
#if __has_include(<QtGui/QHelpEvent>)
#include <QtGui/QHelpEvent>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHelpEvent 1
#endif
#if __has_include(<QtGui/QHideEvent>)
#include <QtGui/QHideEvent>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHideEvent 1
#endif
#if __has_include(<QtGui/QHoverEvent>)
#include <QtGui/QHoverEvent>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHoverEvent 1
#endif
#if __has_include(<QtGui/QIcon>)
#include <QtGui/QIcon>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QIcon 1
#endif
#if __has_include(<QtGui/QPointingDevice>)
#include <QtGui/QPointingDevice>
#define KRY_QT6_NATIVE_TYPE_QTGUI_QPOINTINGDEVICE 1
#endif
#include <QtCore/Qt>
#define KRY_QT6_NATIVE_ENUM_QT_KEYBOARDMODIFIERS 1
#if __has_include(<QtCore/QEvent>)
#include <QtCore/QEvent>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT 1
#endif
#if __has_include(<QtGui/QGradient>)
#include <QtGui/QGradient>
#define KRY_QT6_NATIVE_TYPE_QTGUI_QGRADIENT 1
#endif
#if __has_include(<QtCore/QPoint>)
#include <QtCore/QPoint>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINT 1
#endif
#if __has_include(<QtCore/QPointF>)
#include <QtCore/QPointF>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINTF 1
#endif
#if __has_include(<QtGui/QFont>)
#include <QtGui/QFont>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONT 1
#endif
#if __has_include(<QtGui/QFontMetrics>)
#include <QtGui/QFontMetrics>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONTMETRICS 1
#endif
#if __has_include(<QtGui/QFontMetricsF>)
#include <QtGui/QFontMetricsF>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONTMETRICSF 1
#endif
#if __has_include(<QtGui/QFontVariableAxis>)
#include <QtGui/QFontVariableAxis>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONTVARIABLEAXIS 1
#endif
#if __has_include(<QtGui/QGlyphRun>)
#include <QtGui/QGlyphRun>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QGLYPHRUN 1
#endif
#if __has_include(<QtGui/QIcon>)
#include <QtGui/QIcon>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QICON 1
#endif
#if __has_include(<QtGui/QPixmap>)
#include <QtGui/QPixmap>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP 1
#endif

namespace {
template <typename T, typename... Args>
QVariant makeQtValue(Args &&...args) {
    if constexpr (QMetaTypeId2<T>::Defined && std::is_copy_constructible_v<T> && std::is_constructible_v<T, Args...>) return QVariant::fromValue<T>(T(std::forward<Args>(args)...));
    else return {};
}
}

namespace kry_qt6_generated {
bool construct_value_qtgui_3(const QString &moduleName, const QString &className, const QJsonArray &args, QVariant *output, QString *error) {
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QFontMetricsF") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QFontMetricsF) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONT)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QFont>::Defined && std::is_copy_constructible_v<QFont> && std::is_default_constructible_v<QFont>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QFont>(), error);
            if (!converted0.isValid()) return QVariant();
            const QFont arg0 = converted0.value<QFont>();
            return makeQtValue<QFontMetricsF>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QFontMetricsF) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONTMETRICS)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QFontMetrics>::Defined && std::is_copy_constructible_v<QFontMetrics> && std::is_default_constructible_v<QFontMetrics>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QFontMetrics>(), error);
            if (!converted0.isValid()) return QVariant();
            const QFontMetrics arg0 = converted0.value<QFontMetrics>();
            return makeQtValue<QFontMetricsF>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QFontMetricsF) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONTMETRICSF)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QFontMetricsF>::Defined && std::is_copy_constructible_v<QFontMetricsF> && std::is_default_constructible_v<QFontMetricsF>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QFontMetricsF>(), error);
            if (!converted0.isValid()) return QVariant();
            const QFontMetricsF arg0 = converted0.value<QFontMetricsF>();
            return makeQtValue<QFontMetricsF>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QFontVariableAxis") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QFontVariableAxis)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QFontVariableAxis>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QFontVariableAxis") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QFontVariableAxis) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONTVARIABLEAXIS)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QFontVariableAxis>::Defined && std::is_copy_constructible_v<QFontVariableAxis> && std::is_default_constructible_v<QFontVariableAxis>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QFontVariableAxis>(), error);
            if (!converted0.isValid()) return QVariant();
            const QFontVariableAxis arg0 = converted0.value<QFontVariableAxis>();
            return makeQtValue<QFontVariableAxis>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QGlyphRun") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QGlyphRun)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QGlyphRun>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QGlyphRun") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QGlyphRun) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QGLYPHRUN)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QGlyphRun>::Defined && std::is_copy_constructible_v<QGlyphRun> && std::is_default_constructible_v<QGlyphRun>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QGlyphRun>(), error);
            if (!converted0.isValid()) return QVariant();
            const QGlyphRun arg0 = converted0.value<QGlyphRun>();
            return makeQtValue<QGlyphRun>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QGradient") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QGradient)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QGradient>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QGradient") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QGradient) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QGRADIENT)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QGradient::Preset>::Defined && std::is_copy_constructible_v<QGradient::Preset> && std::is_default_constructible_v<QGradient::Preset>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QGradient::Preset>(), error);
            if (!converted0.isValid()) return QVariant();
            QGradient::Preset arg0 = converted0.value<QGradient::Preset>();
            return makeQtValue<QGradient>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QHelpEvent") && args.size() == 3) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHelpEvent) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINT)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QEvent::Type>::Defined && std::is_copy_constructible_v<QEvent::Type> && std::is_default_constructible_v<QEvent::Type> && QMetaTypeId2<QPoint>::Defined && std::is_copy_constructible_v<QPoint> && std::is_default_constructible_v<QPoint>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QEvent::Type>(), error);
            if (!converted0.isValid()) return QVariant();
            QEvent::Type arg0 = converted0.value<QEvent::Type>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QPoint>(), error);
            if (!converted1.isValid()) return QVariant();
            const QPoint arg1 = converted1.value<QPoint>();
            const QVariant converted2 = kry_qt6_direct::fromJson(args.at(2), QMetaType::fromType<QPoint>(), error);
            if (!converted2.isValid()) return QVariant();
            const QPoint arg2 = converted2.value<QPoint>();
            return makeQtValue<QHelpEvent>(arg0, arg1, arg2);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QHideEvent") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHideEvent)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QHideEvent>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QHoverEvent") && args.size() == 3) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHoverEvent) && defined(KRY_QT6_NATIVE_ENUM_QT_KEYBOARDMODIFIERS) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QPOINTINGDEVICE) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINTF)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QEvent::Type>::Defined && std::is_copy_constructible_v<QEvent::Type> && std::is_default_constructible_v<QEvent::Type> && QMetaTypeId2<QPointF>::Defined && std::is_copy_constructible_v<QPointF> && std::is_default_constructible_v<QPointF>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QEvent::Type>(), error);
            if (!converted0.isValid()) return QVariant();
            QEvent::Type arg0 = converted0.value<QEvent::Type>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QPointF>(), error);
            if (!converted1.isValid()) return QVariant();
            const QPointF arg1 = converted1.value<QPointF>();
            const QVariant converted2 = kry_qt6_direct::fromJson(args.at(2), QMetaType::fromType<QPointF>(), error);
            if (!converted2.isValid()) return QVariant();
            const QPointF arg2 = converted2.value<QPointF>();
            return makeQtValue<QHoverEvent>(arg0, arg1, arg2);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QHoverEvent") && args.size() == 4) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHoverEvent) && defined(KRY_QT6_NATIVE_ENUM_QT_KEYBOARDMODIFIERS) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QPOINTINGDEVICE) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINTF)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QEvent::Type>::Defined && std::is_copy_constructible_v<QEvent::Type> && std::is_default_constructible_v<QEvent::Type> && QMetaTypeId2<QPointF>::Defined && std::is_copy_constructible_v<QPointF> && std::is_default_constructible_v<QPointF>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QEvent::Type>(), error);
            if (!converted0.isValid()) return QVariant();
            QEvent::Type arg0 = converted0.value<QEvent::Type>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QPointF>(), error);
            if (!converted1.isValid()) return QVariant();
            const QPointF arg1 = converted1.value<QPointF>();
            const QVariant converted2 = kry_qt6_direct::fromJson(args.at(2), QMetaType::fromType<QPointF>(), error);
            if (!converted2.isValid()) return QVariant();
            const QPointF arg2 = converted2.value<QPointF>();
            const QVariant converted3 = kry_qt6_direct::fromJson(args.at(3), QMetaType::fromType<QPointF>(), error);
            if (!converted3.isValid()) return QVariant();
            const QPointF arg3 = converted3.value<QPointF>();
            return makeQtValue<QHoverEvent>(arg0, arg1, arg2, arg3);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHoverEvent) && defined(KRY_QT6_NATIVE_ENUM_QT_KEYBOARDMODIFIERS) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QPOINTINGDEVICE) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINTF)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QEvent::Type>::Defined && std::is_copy_constructible_v<QEvent::Type> && std::is_default_constructible_v<QEvent::Type> && QMetaTypeId2<QPointF>::Defined && std::is_copy_constructible_v<QPointF> && std::is_default_constructible_v<QPointF> && QMetaTypeId2<Qt::KeyboardModifiers>::Defined && std::is_copy_constructible_v<Qt::KeyboardModifiers> && std::is_default_constructible_v<Qt::KeyboardModifiers>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QEvent::Type>(), error);
            if (!converted0.isValid()) return QVariant();
            QEvent::Type arg0 = converted0.value<QEvent::Type>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QPointF>(), error);
            if (!converted1.isValid()) return QVariant();
            const QPointF arg1 = converted1.value<QPointF>();
            const QVariant converted2 = kry_qt6_direct::fromJson(args.at(2), QMetaType::fromType<QPointF>(), error);
            if (!converted2.isValid()) return QVariant();
            const QPointF arg2 = converted2.value<QPointF>();
            const QVariant converted3 = kry_qt6_direct::fromJson(args.at(3), QMetaType::fromType<Qt::KeyboardModifiers>(), error);
            if (!converted3.isValid()) return QVariant();
            Qt::KeyboardModifiers arg3 = converted3.value<Qt::KeyboardModifiers>();
            return makeQtValue<QHoverEvent>(arg0, arg1, arg2, arg3);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QHoverEvent") && args.size() == 5) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHoverEvent) && defined(KRY_QT6_NATIVE_ENUM_QT_KEYBOARDMODIFIERS) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QPOINTINGDEVICE) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINTF)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QEvent::Type>::Defined && std::is_copy_constructible_v<QEvent::Type> && std::is_default_constructible_v<QEvent::Type> && QMetaTypeId2<QPointF>::Defined && std::is_copy_constructible_v<QPointF> && std::is_default_constructible_v<QPointF> && QMetaTypeId2<Qt::KeyboardModifiers>::Defined && std::is_copy_constructible_v<Qt::KeyboardModifiers> && std::is_default_constructible_v<Qt::KeyboardModifiers>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QEvent::Type>(), error);
            if (!converted0.isValid()) return QVariant();
            QEvent::Type arg0 = converted0.value<QEvent::Type>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QPointF>(), error);
            if (!converted1.isValid()) return QVariant();
            const QPointF arg1 = converted1.value<QPointF>();
            const QVariant converted2 = kry_qt6_direct::fromJson(args.at(2), QMetaType::fromType<QPointF>(), error);
            if (!converted2.isValid()) return QVariant();
            const QPointF arg2 = converted2.value<QPointF>();
            const QVariant converted3 = kry_qt6_direct::fromJson(args.at(3), QMetaType::fromType<QPointF>(), error);
            if (!converted3.isValid()) return QVariant();
            const QPointF arg3 = converted3.value<QPointF>();
            const QVariant converted4 = kry_qt6_direct::fromJson(args.at(4), QMetaType::fromType<Qt::KeyboardModifiers>(), error);
            if (!converted4.isValid()) return QVariant();
            Qt::KeyboardModifiers arg4 = converted4.value<Qt::KeyboardModifiers>();
            return makeQtValue<QHoverEvent>(arg0, arg1, arg2, arg3, arg4);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHoverEvent) && defined(KRY_QT6_NATIVE_ENUM_QT_KEYBOARDMODIFIERS) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QPOINTINGDEVICE) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINTF)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QEvent::Type>::Defined && std::is_copy_constructible_v<QEvent::Type> && std::is_default_constructible_v<QEvent::Type> && QMetaTypeId2<QPointF>::Defined && std::is_copy_constructible_v<QPointF> && std::is_default_constructible_v<QPointF> && QMetaTypeId2<Qt::KeyboardModifiers>::Defined && std::is_copy_constructible_v<Qt::KeyboardModifiers> && std::is_default_constructible_v<Qt::KeyboardModifiers>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QEvent::Type>(), error);
            if (!converted0.isValid()) return QVariant();
            QEvent::Type arg0 = converted0.value<QEvent::Type>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QPointF>(), error);
            if (!converted1.isValid()) return QVariant();
            const QPointF arg1 = converted1.value<QPointF>();
            const QVariant converted2 = kry_qt6_direct::fromJson(args.at(2), QMetaType::fromType<QPointF>(), error);
            if (!converted2.isValid()) return QVariant();
            const QPointF arg2 = converted2.value<QPointF>();
            const QVariant converted3 = kry_qt6_direct::fromJson(args.at(3), QMetaType::fromType<Qt::KeyboardModifiers>(), error);
            if (!converted3.isValid()) return QVariant();
            Qt::KeyboardModifiers arg3 = converted3.value<Qt::KeyboardModifiers>();
            if (args.at(4).isNull()) { *error = QStringLiteral("argument 4 cannot be null"); return QVariant(); }
            const QVariant converted4 = kry_qt6_direct::fromJson(args.at(4), QMetaType::fromType<QPointingDevice*>(), error);
            if (!converted4.isValid()) return QVariant();
            QPointingDevice* const arg4 = converted4.value<QPointingDevice*>();
            return makeQtValue<QHoverEvent>(arg0, arg1, arg2, arg3, arg4);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QHoverEvent") && args.size() == 6) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHoverEvent) && defined(KRY_QT6_NATIVE_ENUM_QT_KEYBOARDMODIFIERS) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QPOINTINGDEVICE) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINTF)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QEvent::Type>::Defined && std::is_copy_constructible_v<QEvent::Type> && std::is_default_constructible_v<QEvent::Type> && QMetaTypeId2<QPointF>::Defined && std::is_copy_constructible_v<QPointF> && std::is_default_constructible_v<QPointF> && QMetaTypeId2<Qt::KeyboardModifiers>::Defined && std::is_copy_constructible_v<Qt::KeyboardModifiers> && std::is_default_constructible_v<Qt::KeyboardModifiers>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QEvent::Type>(), error);
            if (!converted0.isValid()) return QVariant();
            QEvent::Type arg0 = converted0.value<QEvent::Type>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QPointF>(), error);
            if (!converted1.isValid()) return QVariant();
            const QPointF arg1 = converted1.value<QPointF>();
            const QVariant converted2 = kry_qt6_direct::fromJson(args.at(2), QMetaType::fromType<QPointF>(), error);
            if (!converted2.isValid()) return QVariant();
            const QPointF arg2 = converted2.value<QPointF>();
            const QVariant converted3 = kry_qt6_direct::fromJson(args.at(3), QMetaType::fromType<QPointF>(), error);
            if (!converted3.isValid()) return QVariant();
            const QPointF arg3 = converted3.value<QPointF>();
            const QVariant converted4 = kry_qt6_direct::fromJson(args.at(4), QMetaType::fromType<Qt::KeyboardModifiers>(), error);
            if (!converted4.isValid()) return QVariant();
            Qt::KeyboardModifiers arg4 = converted4.value<Qt::KeyboardModifiers>();
            if (args.at(5).isNull()) { *error = QStringLiteral("argument 5 cannot be null"); return QVariant(); }
            const QVariant converted5 = kry_qt6_direct::fromJson(args.at(5), QMetaType::fromType<QPointingDevice*>(), error);
            if (!converted5.isValid()) return QVariant();
            QPointingDevice* const arg5 = converted5.value<QPointingDevice*>();
            return makeQtValue<QHoverEvent>(arg0, arg1, arg2, arg3, arg4, arg5);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QIcon") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QIcon)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QIcon>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtGui")) &&
        className == QLatin1String("QIcon") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QIcon) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QPixmap>::Defined && std::is_copy_constructible_v<QPixmap> && std::is_default_constructible_v<QPixmap>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QPixmap>(), error);
            if (!converted0.isValid()) return QVariant();
            const QPixmap arg0 = converted0.value<QPixmap>();
            return makeQtValue<QIcon>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QIcon) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QICON)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QIcon>::Defined && std::is_copy_constructible_v<QIcon> && std::is_default_constructible_v<QIcon>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QIcon>(), error);
            if (!converted0.isValid()) return QVariant();
            const QIcon arg0 = converted0.value<QIcon>();
            return makeQtValue<QIcon>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QIcon)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return QVariant(); }
            const QString arg0 = args.at(0).toString();
            return makeQtValue<QIcon>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    return false;
}
QStringList value_constructor_classes_qtgui_3() {
    QStringList result;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QFontMetricsF) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONT) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONTMETRICS) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONTMETRICSF)
    if ((QMetaTypeId2<QFontMetricsF>::Defined && std::is_copy_constructible_v<QFontMetricsF> && std::is_constructible_v<QFontMetricsF, QFont>) || (QMetaTypeId2<QFontMetricsF>::Defined && std::is_copy_constructible_v<QFontMetricsF> && std::is_constructible_v<QFontMetricsF, QFontMetrics>) || (QMetaTypeId2<QFontMetricsF>::Defined && std::is_copy_constructible_v<QFontMetricsF> && std::is_constructible_v<QFontMetricsF, QFontMetricsF>)) result.append(QStringLiteral("QFontMetricsF"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QFontVariableAxis) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QFONTVARIABLEAXIS)
    if ((QMetaTypeId2<QFontVariableAxis>::Defined && std::is_copy_constructible_v<QFontVariableAxis> && std::is_constructible_v<QFontVariableAxis>) || (QMetaTypeId2<QFontVariableAxis>::Defined && std::is_copy_constructible_v<QFontVariableAxis> && std::is_constructible_v<QFontVariableAxis, QFontVariableAxis>)) result.append(QStringLiteral("QFontVariableAxis"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QGlyphRun) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QGLYPHRUN)
    if ((QMetaTypeId2<QGlyphRun>::Defined && std::is_copy_constructible_v<QGlyphRun> && std::is_constructible_v<QGlyphRun>) || (QMetaTypeId2<QGlyphRun>::Defined && std::is_copy_constructible_v<QGlyphRun> && std::is_constructible_v<QGlyphRun, QGlyphRun>)) result.append(QStringLiteral("QGlyphRun"));
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTGUI_QGRADIENT) && defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QGradient)
    if ((QMetaTypeId2<QGradient>::Defined && std::is_copy_constructible_v<QGradient> && std::is_constructible_v<QGradient>) || (QMetaTypeId2<QGradient>::Defined && std::is_copy_constructible_v<QGradient> && std::is_constructible_v<QGradient, QGradient::Preset>)) result.append(QStringLiteral("QGradient"));
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHelpEvent) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINT)
    if ((QMetaTypeId2<QHelpEvent>::Defined && std::is_copy_constructible_v<QHelpEvent> && std::is_constructible_v<QHelpEvent, QEvent::Type, QPoint, QPoint>)) result.append(QStringLiteral("QHelpEvent"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHideEvent)
    if ((QMetaTypeId2<QHideEvent>::Defined && std::is_copy_constructible_v<QHideEvent> && std::is_constructible_v<QHideEvent>)) result.append(QStringLiteral("QHideEvent"));
#endif
#if defined(KRY_QT6_NATIVE_ENUM_QT_KEYBOARDMODIFIERS) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QPOINTINGDEVICE) && defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QHoverEvent) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPOINTF)
    if ((QMetaTypeId2<QHoverEvent>::Defined && std::is_copy_constructible_v<QHoverEvent> && std::is_constructible_v<QHoverEvent, QEvent::Type, QPointF, QPointF, QPointF, Qt::KeyboardModifiers, QPointingDevice*>) || (QMetaTypeId2<QHoverEvent>::Defined && std::is_copy_constructible_v<QHoverEvent> && std::is_constructible_v<QHoverEvent, QEvent::Type, QPointF, QPointF, Qt::KeyboardModifiers, QPointingDevice*>)) result.append(QStringLiteral("QHoverEvent"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTGUI_QIcon) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QICON) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP)
    if ((QMetaTypeId2<QIcon>::Defined && std::is_copy_constructible_v<QIcon> && std::is_constructible_v<QIcon>) || (QMetaTypeId2<QIcon>::Defined && std::is_copy_constructible_v<QIcon> && std::is_constructible_v<QIcon, QPixmap>) || (QMetaTypeId2<QIcon>::Defined && std::is_copy_constructible_v<QIcon> && std::is_constructible_v<QIcon, QIcon>) || (QMetaTypeId2<QIcon>::Defined && std::is_copy_constructible_v<QIcon> && std::is_constructible_v<QIcon, QString>)) result.append(QStringLiteral("QIcon"));
#endif
    return result;
}
} // namespace kry_qt6_generated
