// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QStringList>
#include <type_traits>
#include <utility>

#if __has_include(<QtOpenGL/QOpenGLPixelTransferOptions>)
#include <QtOpenGL/QOpenGLPixelTransferOptions>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLPixelTransferOptions 1
#endif
#if __has_include(<QtOpenGL/QOpenGLTexture>)
#include <QtOpenGL/QOpenGLTexture>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLTexture 1
#endif
#if __has_include(<QtOpenGL/QOpenGLTextureBlitter>)
#include <QtOpenGL/QOpenGLTextureBlitter>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLTextureBlitter 1
#endif
#if __has_include(<QtOpenGL/QOpenGLVersionProfile>)
#include <QtOpenGL/QOpenGLVersionProfile>
#define KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLVersionProfile 1
#endif
#if __has_include(<QtOpenGL/QOpenGLTexture>)
#include <QtOpenGL/QOpenGLTexture>
#define KRY_QT6_NATIVE_TYPE_QTOPENGL_QOPENGLTEXTURE 1
#endif
#if __has_include(<QtGui/QImage>)
#include <QtGui/QImage>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QIMAGE 1
#endif
#if __has_include(<QtGui/QSurfaceFormat>)
#include <QtGui/QSurfaceFormat>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QSURFACEFORMAT 1
#endif
#if __has_include(<QtOpenGL/QOpenGLPixelTransferOptions>)
#include <QtOpenGL/QOpenGLPixelTransferOptions>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTOPENGL_QOPENGLPIXELTRANSFEROPTIONS 1
#endif
#if __has_include(<QtOpenGL/QOpenGLVersionProfile>)
#include <QtOpenGL/QOpenGLVersionProfile>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTOPENGL_QOPENGLVERSIONPROFILE 1
#endif

namespace {
template <typename T, typename... Args>
QVariant makeQtValue(Args &&...args) {
    if constexpr (QMetaTypeId2<T>::Defined && std::is_copy_constructible_v<T> && std::is_constructible_v<T, Args...>) return QVariant::fromValue<T>(T(std::forward<Args>(args)...));
    else return {};
}
}

namespace kry_qt6_generated {
bool construct_value_qtopengl_1(const QString &moduleName, const QString &className, const QJsonArray &args, QVariant *output, QString *error) {
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtOpenGL")) &&
        className == QLatin1String("QOpenGLPixelTransferOptions") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLPixelTransferOptions)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QOpenGLPixelTransferOptions>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtOpenGL")) &&
        className == QLatin1String("QOpenGLPixelTransferOptions") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLPixelTransferOptions) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTOPENGL_QOPENGLPIXELTRANSFEROPTIONS)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QOpenGLPixelTransferOptions>::Defined && std::is_copy_constructible_v<QOpenGLPixelTransferOptions> && std::is_default_constructible_v<QOpenGLPixelTransferOptions>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QOpenGLPixelTransferOptions>(), error);
            if (!converted0.isValid()) return QVariant();
            const QOpenGLPixelTransferOptions arg0 = converted0.value<QOpenGLPixelTransferOptions>();
            return makeQtValue<QOpenGLPixelTransferOptions>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtOpenGL")) &&
        className == QLatin1String("QOpenGLTexture") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLTexture) && defined(KRY_QT6_NATIVE_TYPE_QTOPENGL_QOPENGLTEXTURE)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QOpenGLTexture::Target>::Defined && std::is_copy_constructible_v<QOpenGLTexture::Target> && std::is_default_constructible_v<QOpenGLTexture::Target>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QOpenGLTexture::Target>(), error);
            if (!converted0.isValid()) return QVariant();
            QOpenGLTexture::Target arg0 = converted0.value<QOpenGLTexture::Target>();
            return makeQtValue<QOpenGLTexture>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLTexture) && defined(KRY_QT6_NATIVE_TYPE_QTOPENGL_QOPENGLTEXTURE) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QIMAGE)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QImage>::Defined && std::is_copy_constructible_v<QImage> && std::is_default_constructible_v<QImage>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QImage>(), error);
            if (!converted0.isValid()) return QVariant();
            const QImage arg0 = converted0.value<QImage>();
            return makeQtValue<QOpenGLTexture>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtOpenGL")) &&
        className == QLatin1String("QOpenGLTexture") && args.size() == 2) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLTexture) && defined(KRY_QT6_NATIVE_TYPE_QTOPENGL_QOPENGLTEXTURE) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QIMAGE)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QImage>::Defined && std::is_copy_constructible_v<QImage> && std::is_default_constructible_v<QImage> && QMetaTypeId2<QOpenGLTexture::MipMapGeneration>::Defined && std::is_copy_constructible_v<QOpenGLTexture::MipMapGeneration> && std::is_default_constructible_v<QOpenGLTexture::MipMapGeneration>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QImage>(), error);
            if (!converted0.isValid()) return QVariant();
            const QImage arg0 = converted0.value<QImage>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QOpenGLTexture::MipMapGeneration>(), error);
            if (!converted1.isValid()) return QVariant();
            QOpenGLTexture::MipMapGeneration arg1 = converted1.value<QOpenGLTexture::MipMapGeneration>();
            return makeQtValue<QOpenGLTexture>(arg0, arg1);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtOpenGL")) &&
        className == QLatin1String("QOpenGLTextureBlitter") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLTextureBlitter)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QOpenGLTextureBlitter>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtOpenGL")) &&
        className == QLatin1String("QOpenGLVersionProfile") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLVersionProfile)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            return makeQtValue<QOpenGLVersionProfile>();
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtOpenGL")) &&
        className == QLatin1String("QOpenGLVersionProfile") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLVersionProfile) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QSURFACEFORMAT)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QSurfaceFormat>::Defined && std::is_copy_constructible_v<QSurfaceFormat> && std::is_default_constructible_v<QSurfaceFormat>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QSurfaceFormat>(), error);
            if (!converted0.isValid()) return QVariant();
            const QSurfaceFormat arg0 = converted0.value<QSurfaceFormat>();
            return makeQtValue<QOpenGLVersionProfile>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLVersionProfile) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTOPENGL_QOPENGLVERSIONPROFILE)
        {
        QString candidateError;
        auto build_candidate = [&](auto enable) -> QVariant {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QOpenGLVersionProfile>::Defined && std::is_copy_constructible_v<QOpenGLVersionProfile> && std::is_default_constructible_v<QOpenGLVersionProfile>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QOpenGLVersionProfile>(), error);
            if (!converted0.isValid()) return QVariant();
            const QOpenGLVersionProfile arg0 = converted0.value<QOpenGLVersionProfile>();
            return makeQtValue<QOpenGLVersionProfile>(arg0);
            }
            return {};
        };
        QVariant created = build_candidate(std::true_type{});
        if (created.isValid()) { *output = std::move(created); return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    return false;
}
QStringList value_constructor_classes_qtopengl_1() {
    QStringList result;
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLPixelTransferOptions) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTOPENGL_QOPENGLPIXELTRANSFEROPTIONS)
    if ((QMetaTypeId2<QOpenGLPixelTransferOptions>::Defined && std::is_copy_constructible_v<QOpenGLPixelTransferOptions> && std::is_constructible_v<QOpenGLPixelTransferOptions>) || (QMetaTypeId2<QOpenGLPixelTransferOptions>::Defined && std::is_copy_constructible_v<QOpenGLPixelTransferOptions> && std::is_constructible_v<QOpenGLPixelTransferOptions, QOpenGLPixelTransferOptions>)) result.append(QStringLiteral("QOpenGLPixelTransferOptions"));
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTOPENGL_QOPENGLTEXTURE) && defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLTexture) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QIMAGE)
    if ((QMetaTypeId2<QOpenGLTexture>::Defined && std::is_copy_constructible_v<QOpenGLTexture> && std::is_constructible_v<QOpenGLTexture, QOpenGLTexture::Target>) || (QMetaTypeId2<QOpenGLTexture>::Defined && std::is_copy_constructible_v<QOpenGLTexture> && std::is_constructible_v<QOpenGLTexture, QImage, QOpenGLTexture::MipMapGeneration>)) result.append(QStringLiteral("QOpenGLTexture"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLTextureBlitter)
    if ((QMetaTypeId2<QOpenGLTextureBlitter>::Defined && std::is_copy_constructible_v<QOpenGLTextureBlitter> && std::is_constructible_v<QOpenGLTextureBlitter>)) result.append(QStringLiteral("QOpenGLTextureBlitter"));
#endif
#if defined(KRY_QT6_NATIVE_VALUE_CONSTRUCTORS_QTOPENGL_QOpenGLVersionProfile) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QSURFACEFORMAT) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTOPENGL_QOPENGLVERSIONPROFILE)
    if ((QMetaTypeId2<QOpenGLVersionProfile>::Defined && std::is_copy_constructible_v<QOpenGLVersionProfile> && std::is_constructible_v<QOpenGLVersionProfile>) || (QMetaTypeId2<QOpenGLVersionProfile>::Defined && std::is_copy_constructible_v<QOpenGLVersionProfile> && std::is_constructible_v<QOpenGLVersionProfile, QSurfaceFormat>) || (QMetaTypeId2<QOpenGLVersionProfile>::Defined && std::is_copy_constructible_v<QOpenGLVersionProfile> && std::is_constructible_v<QOpenGLVersionProfile, QOpenGLVersionProfile>)) result.append(QStringLiteral("QOpenGLVersionProfile"));
#endif
    return result;
}
} // namespace kry_qt6_generated
