// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QMetaType>
#include <QtCore/QObject>
#include <QtCore/QVariant>
#include <QtCore/QString>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QHash>
#include <QtCore/QStringList>
#include <type_traits>
#include <cmath>
#include <limits>

#if __has_include(<QtWebEngineQuick/QQuickWebEngineProfile>)
#include <QtWebEngineQuick/QQuickWebEngineProfile>
#define KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile 1
#endif
#if __has_include(<QtWebEngineCore/QWebEngineCookieStore>)
#include <QtWebEngineCore/QWebEngineCookieStore>
#define KRY_QT6_NATIVE_TYPE_QTWEBENGINECORE_QWEBENGINECOOKIESTORE 1
#endif
#if __has_include(<QtWebEngineCore/QWebEngineUrlRequestInterceptor>)
#include <QtWebEngineCore/QWebEngineUrlRequestInterceptor>
#define KRY_QT6_NATIVE_TYPE_QTWEBENGINECORE_QWEBENGINEURLREQUESTINTERCEPTOR 1
#endif
#if __has_include(<QtWebEngineCore/QWebEngineUrlSchemeHandler>)
#include <QtWebEngineCore/QWebEngineUrlSchemeHandler>
#define KRY_QT6_NATIVE_TYPE_QTWEBENGINECORE_QWEBENGINEURLSCHEMEHANDLER 1
#endif
#if __has_include(<QtWebEngineQuick/QQuickWebEngineProfile>)
#include <QtWebEngineQuick/QQuickWebEngineProfile>
#define KRY_QT6_NATIVE_TYPE_QTWEBENGINEQUICK_QQUICKWEBENGINEPROFILE 1
#endif
#if __has_include(<QtWebEngineQuick/QQuickWebEngineProfile>)
#include <QtWebEngineQuick/QQuickWebEngineProfile>
#define KRY_QT6_NATIVE_TYPE_QTWEBENGINEQUICK_QQUICKWEBENGINEPROFILE 1
#endif
#if __has_include(<QtCore/QByteArray>)
#include <QtCore/QByteArray>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY 1
#endif

namespace kry_qt6_direct {
bool invoke_qtwebenginequick_0(QObject *object, const QString &className, const QString &signature, const QJsonArray &args, QJsonValue *output, QString *error) {
    auto invoke_signature_0 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("cachePath()")) {
        if (args.size() != 0) { *error = QStringLiteral("cachePath() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = QJsonValue(QString(target->cachePath()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_0(std::true_type{})) return true;
    auto invoke_signature_1 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("clearHttpCache()")) {
        if (args.size() != 0) { *error = QStringLiteral("clearHttpCache() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->clearHttpCache();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_1(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINECORE_QWEBENGINECOOKIESTORE)
    auto invoke_signature_2 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("cookieStore()")) {
        if (args.size() != 0) { *error = QStringLiteral("cookieStore() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->cookieStore())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_2(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINEQUICK_QQUICKWEBENGINEPROFILE)
    auto invoke_signature_3 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("defaultProfile()")) {
        if (args.size() != 0) { *error = QStringLiteral("defaultProfile() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (className == QLatin1String("QtWebEngineQuick.QQuickWebEngineProfile")) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(QQuickWebEngineProfile::defaultProfile())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_3(std::true_type{})) return true;
#endif
    auto invoke_signature_4 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("downloadPath()")) {
        if (args.size() != 0) { *error = QStringLiteral("downloadPath() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = QJsonValue(QString(target->downloadPath()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_4(std::true_type{})) return true;
    auto invoke_signature_5 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("httpAcceptLanguage()")) {
        if (args.size() != 0) { *error = QStringLiteral("httpAcceptLanguage() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = QJsonValue(QString(target->httpAcceptLanguage()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_5(std::true_type{})) return true;
    auto invoke_signature_6 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("httpCacheMaximumSize()")) {
        if (args.size() != 0) { *error = QStringLiteral("httpCacheMaximumSize() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<double>(target->httpCacheMaximumSize()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_6(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINEQUICK_QQUICKWEBENGINEPROFILE)
    auto invoke_signature_7 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("httpCacheType()")) {
        if (args.size() != 0) { *error = QStringLiteral("httpCacheType() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QQuickWebEngineProfile::HttpCacheType>(target->httpCacheType()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_7(std::true_type{})) return true;
#endif
    auto invoke_signature_8 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("httpUserAgent()")) {
        if (args.size() != 0) { *error = QStringLiteral("httpUserAgent() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = QJsonValue(QString(target->httpUserAgent()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_8(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINECORE_QWEBENGINEURLSCHEMEHANDLER) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
    auto invoke_signature_9 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QByteArray>::Defined && std::is_copy_constructible_v<QByteArray> && std::is_default_constructible_v<QByteArray>) {
    if (signature == QLatin1String("installUrlSchemeHandler(QByteArray,QWebEngineUrlSchemeHandler*)")) {
        if (args.size() != 2) { *error = QStringLiteral("installUrlSchemeHandler(QByteArray,QWebEngineUrlSchemeHandler*) expects 2 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QByteArray>(), error);
            if (!converted0.isValid()) return true;
            const QByteArray arg0 = converted0.value<QByteArray>();
            if (args.at(1).isNull()) { *error = QStringLiteral("argument 1 cannot be null"); return true; }
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QWebEngineUrlSchemeHandler*>(), error);
            if (!converted1.isValid()) return true;
            QWebEngineUrlSchemeHandler* const arg1 = converted1.value<QWebEngineUrlSchemeHandler*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->installUrlSchemeHandler(arg0, arg1);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_9(std::true_type{})) return true;
#endif
    auto invoke_signature_10 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("isOffTheRecord()")) {
        if (args.size() != 0) { *error = QStringLiteral("isOffTheRecord() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->isOffTheRecord()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_10(std::true_type{})) return true;
    auto invoke_signature_11 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("isSpellCheckEnabled()")) {
        if (args.size() != 0) { *error = QStringLiteral("isSpellCheckEnabled() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->isSpellCheckEnabled()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_11(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINEQUICK_QQUICKWEBENGINEPROFILE)
    auto invoke_signature_12 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("persistentCookiesPolicy()")) {
        if (args.size() != 0) { *error = QStringLiteral("persistentCookiesPolicy() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QQuickWebEngineProfile::PersistentCookiesPolicy>(target->persistentCookiesPolicy()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_12(std::true_type{})) return true;
#endif
    auto invoke_signature_13 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("persistentStoragePath()")) {
        if (args.size() != 0) { *error = QStringLiteral("persistentStoragePath() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = QJsonValue(QString(target->persistentStoragePath()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_13(std::true_type{})) return true;
    auto invoke_signature_14 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("removeAllUrlSchemeHandlers()")) {
        if (args.size() != 0) { *error = QStringLiteral("removeAllUrlSchemeHandlers() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->removeAllUrlSchemeHandlers();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_14(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
    auto invoke_signature_15 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QByteArray>::Defined && std::is_copy_constructible_v<QByteArray> && std::is_default_constructible_v<QByteArray>) {
    if (signature == QLatin1String("removeUrlScheme(QByteArray)")) {
        if (args.size() != 1) { *error = QStringLiteral("removeUrlScheme(QByteArray) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QByteArray>(), error);
            if (!converted0.isValid()) return true;
            const QByteArray arg0 = converted0.value<QByteArray>();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->removeUrlScheme(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_15(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINECORE_QWEBENGINEURLSCHEMEHANDLER)
    auto invoke_signature_16 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("removeUrlSchemeHandler(QWebEngineUrlSchemeHandler*)")) {
        if (args.size() != 1) { *error = QStringLiteral("removeUrlSchemeHandler(QWebEngineUrlSchemeHandler*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QWebEngineUrlSchemeHandler*>(), error);
            if (!converted0.isValid()) return true;
            QWebEngineUrlSchemeHandler* const arg0 = converted0.value<QWebEngineUrlSchemeHandler*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->removeUrlSchemeHandler(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_16(std::true_type{})) return true;
#endif
    auto invoke_signature_17 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setCachePath(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("setCachePath(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setCachePath(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_17(std::true_type{})) return true;
    auto invoke_signature_18 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setDownloadPath(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("setDownloadPath(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setDownloadPath(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_18(std::true_type{})) return true;
    auto invoke_signature_19 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setHttpAcceptLanguage(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("setHttpAcceptLanguage(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setHttpAcceptLanguage(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_19(std::true_type{})) return true;
    auto invoke_signature_20 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setHttpCacheMaximumSize(int)")) {
        if (args.size() != 1) { *error = QStringLiteral("setHttpCacheMaximumSize(int) expects 1 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setHttpCacheMaximumSize(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_20(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINEQUICK_QQUICKWEBENGINEPROFILE)
    auto invoke_signature_21 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QQuickWebEngineProfile::HttpCacheType>::Defined && std::is_copy_constructible_v<QQuickWebEngineProfile::HttpCacheType> && std::is_default_constructible_v<QQuickWebEngineProfile::HttpCacheType>) {
    if (signature == QLatin1String("setHttpCacheType(QQuickWebEngineProfile::HttpCacheType)")) {
        if (args.size() != 1) { *error = QStringLiteral("setHttpCacheType(QQuickWebEngineProfile::HttpCacheType) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QQuickWebEngineProfile::HttpCacheType>(), error);
            if (!converted0.isValid()) return true;
            QQuickWebEngineProfile::HttpCacheType arg0 = converted0.value<QQuickWebEngineProfile::HttpCacheType>();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setHttpCacheType(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_21(std::true_type{})) return true;
#endif
    auto invoke_signature_22 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setHttpUserAgent(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("setHttpUserAgent(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setHttpUserAgent(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_22(std::true_type{})) return true;
    auto invoke_signature_23 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setOffTheRecord(bool)")) {
        if (args.size() != 1) { *error = QStringLiteral("setOffTheRecord(bool) expects 1 argument(s)"); return true; }
            if (!args.at(0).isBool()) { *error = QStringLiteral("argument 0 must be a boolean"); return true; }
            const bool arg0 = args.at(0).toBool();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setOffTheRecord(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_23(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINEQUICK_QQUICKWEBENGINEPROFILE)
    auto invoke_signature_24 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QQuickWebEngineProfile::PersistentCookiesPolicy>::Defined && std::is_copy_constructible_v<QQuickWebEngineProfile::PersistentCookiesPolicy> && std::is_default_constructible_v<QQuickWebEngineProfile::PersistentCookiesPolicy>) {
    if (signature == QLatin1String("setPersistentCookiesPolicy(QQuickWebEngineProfile::PersistentCookiesPolicy)")) {
        if (args.size() != 1) { *error = QStringLiteral("setPersistentCookiesPolicy(QQuickWebEngineProfile::PersistentCookiesPolicy) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QQuickWebEngineProfile::PersistentCookiesPolicy>(), error);
            if (!converted0.isValid()) return true;
            QQuickWebEngineProfile::PersistentCookiesPolicy arg0 = converted0.value<QQuickWebEngineProfile::PersistentCookiesPolicy>();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setPersistentCookiesPolicy(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_24(std::true_type{})) return true;
#endif
    auto invoke_signature_25 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setPersistentStoragePath(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("setPersistentStoragePath(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setPersistentStoragePath(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_25(std::true_type{})) return true;
    auto invoke_signature_26 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setSpellCheckEnabled(bool)")) {
        if (args.size() != 1) { *error = QStringLiteral("setSpellCheckEnabled(bool) expects 1 argument(s)"); return true; }
            if (!args.at(0).isBool()) { *error = QStringLiteral("argument 0 must be a boolean"); return true; }
            const bool arg0 = args.at(0).toBool();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setSpellCheckEnabled(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_26(std::true_type{})) return true;
    auto invoke_signature_27 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setSpellCheckLanguages(QStringList)")) {
        if (args.size() != 1) { *error = QStringLiteral("setSpellCheckLanguages(QStringList) expects 1 argument(s)"); return true; }
            if (!args.at(0).isArray()) { *error = QStringLiteral("argument 0 must be an array"); return true; }
            QStringList arg0;
            for (const QJsonValue &entry : args.at(0).toArray()) {
                const QVariant converted = kry_qt6_direct::fromJson(entry, QMetaType::fromType<QString>(), error);
                if (!converted.isValid()) return true;
                arg0.append(converted.value<QString>());
            }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setSpellCheckLanguages(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_27(std::true_type{})) return true;
    auto invoke_signature_28 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setStorageName(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("setStorageName(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setStorageName(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_28(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINECORE_QWEBENGINEURLREQUESTINTERCEPTOR)
    auto invoke_signature_29 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setUrlRequestInterceptor(QWebEngineUrlRequestInterceptor*)")) {
        if (args.size() != 1) { *error = QStringLiteral("setUrlRequestInterceptor(QWebEngineUrlRequestInterceptor*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QWebEngineUrlRequestInterceptor*>(), error);
            if (!converted0.isValid()) return true;
            QWebEngineUrlRequestInterceptor* const arg0 = converted0.value<QWebEngineUrlRequestInterceptor*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                target->setUrlRequestInterceptor(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_29(std::true_type{})) return true;
#endif
    auto invoke_signature_30 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("spellCheckLanguages()")) {
        if (args.size() != 0) { *error = QStringLiteral("spellCheckLanguages() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                QJsonArray values;
                for (const auto &item : target->spellCheckLanguages()) {
                    values.append(kry_qt6_direct::toJson(QVariant::fromValue<QString>(item)));
                }
                *output = values;
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_30(std::true_type{})) return true;
    auto invoke_signature_31 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("storageName()")) {
        if (args.size() != 0) { *error = QStringLiteral("storageName() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = QJsonValue(QString(target->storageName()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_31(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTWEBENGINECORE_QWEBENGINEURLSCHEMEHANDLER) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
    auto invoke_signature_32 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QByteArray>::Defined && std::is_copy_constructible_v<QByteArray> && std::is_default_constructible_v<QByteArray>) {
    if (signature == QLatin1String("urlSchemeHandler(QByteArray)")) {
        if (args.size() != 1) { *error = QStringLiteral("urlSchemeHandler(QByteArray) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QByteArray>(), error);
            if (!converted0.isValid()) return true;
            const QByteArray arg0 = converted0.value<QByteArray>();
#ifdef KRY_QT6_NATIVE_METHODS_QTWEBENGINEQUICK_QQuickWebEngineProfile
        if (auto *target = dynamic_cast<QQuickWebEngineProfile *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->urlSchemeHandler(arg0))));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_32(std::true_type{})) return true;
#endif
    return false;
}
} // namespace kry_qt6_direct
