// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QMetaType>
#include <QtCore/QObject>
#include <QtCore/QVariant>
#include <QtCore/QString>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QHash>
#include <QtCore/QStringList>
#include <type_traits>
#include <cmath>
#include <limits>

#if __has_include(<QtStateMachine/QAbstractState>)
#include <QtStateMachine/QAbstractState>
#define KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractState 1
#endif
#if __has_include(<QtStateMachine/QAbstractTransition>)
#include <QtStateMachine/QAbstractTransition>
#define KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractTransition 1
#endif
#if __has_include(<QtStateMachine/QEventTransition>)
#include <QtStateMachine/QEventTransition>
#define KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QEventTransition 1
#endif
#if __has_include(<QtStateMachine/QHistoryState>)
#include <QtStateMachine/QHistoryState>
#define KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QHistoryState 1
#endif
#if __has_include(<QtStateMachine/QKeyEventTransition>)
#include <QtStateMachine/QKeyEventTransition>
#define KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QKeyEventTransition 1
#endif
#if __has_include(<QtStateMachine/QMouseEventTransition>)
#include <QtStateMachine/QMouseEventTransition>
#define KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QMouseEventTransition 1
#endif
#if __has_include(<QtStateMachine/QSignalTransition>)
#include <QtStateMachine/QSignalTransition>
#define KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QSignalTransition 1
#endif
#if __has_include(<QtStateMachine/QState>)
#include <QtStateMachine/QState>
#define KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState 1
#endif
#if __has_include(<QtStateMachine/QStateMachine>)
#include <QtStateMachine/QStateMachine>
#define KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine 1
#endif
#if __has_include(<QtCore/QObject>)
#include <QtCore/QObject>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT 1
#endif
#if __has_include(<QtStateMachine/QAbstractState>)
#include <QtStateMachine/QAbstractState>
#define KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE 1
#endif
#if __has_include(<QtStateMachine/QAbstractTransition>)
#include <QtStateMachine/QAbstractTransition>
#define KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION 1
#endif
#if __has_include(<QtStateMachine/QState>)
#include <QtStateMachine/QState>
#define KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATE 1
#endif
#if __has_include(<QtStateMachine/QStateMachine>)
#include <QtStateMachine/QStateMachine>
#define KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATEMACHINE 1
#endif
#include <QtCore/Qt>
#define KRY_QT6_NATIVE_ENUM_QT_MOUSEBUTTON 1
#if __has_include(<QtCore/QEvent>)
#include <QtCore/QEvent>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT 1
#endif
#if __has_include(<QtStateMachine/QAbstractTransition>)
#include <QtStateMachine/QAbstractTransition>
#define KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION 1
#endif
#if __has_include(<QtStateMachine/QHistoryState>)
#include <QtStateMachine/QHistoryState>
#define KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QHISTORYSTATE 1
#endif
#if __has_include(<QtStateMachine/QState>)
#include <QtStateMachine/QState>
#define KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATE 1
#endif
#if __has_include(<QtStateMachine/QStateMachine>)
#include <QtStateMachine/QStateMachine>
#define KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATEMACHINE 1
#endif
#if __has_include(<QtCore/QByteArray>)
#include <QtCore/QByteArray>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY 1
#endif
#if __has_include(<QtGui/QPainterPath>)
#include <QtGui/QPainterPath>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPAINTERPATH 1
#endif

namespace kry_qt6_direct {
bool invoke_qtstatemachine_0(QObject *object, const QString &className, const QString &signature, const QJsonArray &args, QJsonValue *output, QString *error) {
    auto invoke_signature_0 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("active()")) {
        if (args.size() != 0) { *error = QStringLiteral("active() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractState
        if (auto *target = dynamic_cast<QAbstractState *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->active()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_0(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_1 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("addState(QAbstractState*)")) {
        if (args.size() != 1) { *error = QStringLiteral("addState(QAbstractState*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractState*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractState* const arg0 = converted0.value<QAbstractState*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                target->addState(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_1(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE) && defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION)
    auto invoke_signature_2 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("addTransition(QAbstractState*)")) {
        if (args.size() != 1) { *error = QStringLiteral("addTransition(QAbstractState*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractState*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractState* const arg0 = converted0.value<QAbstractState*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->addTransition(arg0))));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_2(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION)
    auto invoke_signature_3 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("addTransition(QAbstractTransition*)")) {
        if (args.size() != 1) { *error = QStringLiteral("addTransition(QAbstractTransition*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractTransition*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractTransition* const arg0 = converted0.value<QAbstractTransition*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                target->addTransition(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_3(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_ENUM_QT_MOUSEBUTTON)
    auto invoke_signature_4 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("button()")) {
        if (args.size() != 0) { *error = QStringLiteral("button() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QMouseEventTransition
        if (auto *target = dynamic_cast<QMouseEventTransition *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<Qt::MouseButton>(target->button()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_4(std::true_type{})) return true;
#endif
    auto invoke_signature_5 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("cancelDelayedEvent(int)")) {
        if (args.size() != 1) { *error = QStringLiteral("cancelDelayedEvent(int) expects 1 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->cancelDelayedEvent(arg0)));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_5(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATE)
    auto invoke_signature_6 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("childMode()")) {
        if (args.size() != 0) { *error = QStringLiteral("childMode() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QState::ChildMode>(target->childMode()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_6(std::true_type{})) return true;
#endif
    auto invoke_signature_7 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("clearError()")) {
        if (args.size() != 0) { *error = QStringLiteral("clearError() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                target->clearError();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_7(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_8 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("defaultState()")) {
        if (args.size() != 0) { *error = QStringLiteral("defaultState() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QHistoryState
        if (auto *target = dynamic_cast<QHistoryState *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->defaultState())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_8(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION)
    auto invoke_signature_9 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("defaultTransition()")) {
        if (args.size() != 0) { *error = QStringLiteral("defaultTransition() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QHistoryState
        if (auto *target = dynamic_cast<QHistoryState *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->defaultTransition())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_9(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATEMACHINE)
    auto invoke_signature_10 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("error()")) {
        if (args.size() != 0) { *error = QStringLiteral("error() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QStateMachine::Error>(target->error()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_10(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_11 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("errorState()")) {
        if (args.size() != 0) { *error = QStringLiteral("errorState() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->errorState())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_11(std::true_type{})) return true;
#endif
    auto invoke_signature_12 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("errorString()")) {
        if (args.size() != 0) { *error = QStringLiteral("errorString() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                *output = QJsonValue(QString(target->errorString()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_12(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
    auto invoke_signature_13 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("eventSource()")) {
        if (args.size() != 0) { *error = QStringLiteral("eventSource() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QEventTransition
        if (auto *target = dynamic_cast<QEventTransition *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->eventSource())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_13(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT)
    auto invoke_signature_14 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("eventType()")) {
        if (args.size() != 0) { *error = QStringLiteral("eventType() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QEventTransition
        if (auto *target = dynamic_cast<QEventTransition *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QEvent::Type>(target->eventType()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_14(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATE)
    auto invoke_signature_15 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("globalRestorePolicy()")) {
        if (args.size() != 0) { *error = QStringLiteral("globalRestorePolicy() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QState::RestorePolicy>(target->globalRestorePolicy()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_15(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QHISTORYSTATE)
    auto invoke_signature_16 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("historyType()")) {
        if (args.size() != 0) { *error = QStringLiteral("historyType() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QHistoryState
        if (auto *target = dynamic_cast<QHistoryState *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QHistoryState::HistoryType>(target->historyType()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_16(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPAINTERPATH)
    auto invoke_signature_17 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("hitTestPath()")) {
        if (args.size() != 0) { *error = QStringLiteral("hitTestPath() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QMouseEventTransition
        if (auto *target = dynamic_cast<QMouseEventTransition *>(object); target != nullptr) {
                const QVariant convertedResult = kry_qt6_direct::storeValue<QPainterPath>(target->hitTestPath());
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_17(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_18 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("initialState()")) {
        if (args.size() != 0) { *error = QStringLiteral("initialState() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->initialState())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_18(std::true_type{})) return true;
#endif
    auto invoke_signature_19 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("isAnimated()")) {
        if (args.size() != 0) { *error = QStringLiteral("isAnimated() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->isAnimated()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_19(std::true_type{})) return true;
    auto invoke_signature_20 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("isRunning()")) {
        if (args.size() != 0) { *error = QStringLiteral("isRunning() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->isRunning()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_20(std::true_type{})) return true;
    auto invoke_signature_21 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("key()")) {
        if (args.size() != 0) { *error = QStringLiteral("key() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QKeyEventTransition
        if (auto *target = dynamic_cast<QKeyEventTransition *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<double>(target->key()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_21(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATEMACHINE)
    auto invoke_signature_22 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("machine()")) {
        if (args.size() != 0) { *error = QStringLiteral("machine() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractState
        if (auto *target = dynamic_cast<QAbstractState *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->machine())));
            return true;
        }
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractTransition
        if (auto *target = dynamic_cast<QAbstractTransition *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->machine())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_22(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATE)
    auto invoke_signature_23 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("parentState()")) {
        if (args.size() != 0) { *error = QStringLiteral("parentState() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractState
        if (auto *target = dynamic_cast<QAbstractState *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->parentState())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_23(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_24 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("removeState(QAbstractState*)")) {
        if (args.size() != 1) { *error = QStringLiteral("removeState(QAbstractState*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractState*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractState* const arg0 = converted0.value<QAbstractState*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                target->removeState(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_24(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION)
    auto invoke_signature_25 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("removeTransition(QAbstractTransition*)")) {
        if (args.size() != 1) { *error = QStringLiteral("removeTransition(QAbstractTransition*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractTransition*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractTransition* const arg0 = converted0.value<QAbstractTransition*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                target->removeTransition(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_25(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
    auto invoke_signature_26 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("senderObject()")) {
        if (args.size() != 0) { *error = QStringLiteral("senderObject() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QSignalTransition
        if (auto *target = dynamic_cast<QSignalTransition *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->senderObject())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_26(std::true_type{})) return true;
#endif
    auto invoke_signature_27 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setAnimated(bool)")) {
        if (args.size() != 1) { *error = QStringLiteral("setAnimated(bool) expects 1 argument(s)"); return true; }
            if (!args.at(0).isBool()) { *error = QStringLiteral("argument 0 must be a boolean"); return true; }
            const bool arg0 = args.at(0).toBool();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                target->setAnimated(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_27(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_ENUM_QT_MOUSEBUTTON)
    auto invoke_signature_28 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<Qt::MouseButton>::Defined && std::is_copy_constructible_v<Qt::MouseButton> && std::is_default_constructible_v<Qt::MouseButton>) {
    if (signature == QLatin1String("setButton(Qt::MouseButton)")) {
        if (args.size() != 1) { *error = QStringLiteral("setButton(Qt::MouseButton) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<Qt::MouseButton>(), error);
            if (!converted0.isValid()) return true;
            Qt::MouseButton arg0 = converted0.value<Qt::MouseButton>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QMouseEventTransition
        if (auto *target = dynamic_cast<QMouseEventTransition *>(object); target != nullptr) {
                target->setButton(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_28(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATE)
    auto invoke_signature_29 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QState::ChildMode>::Defined && std::is_copy_constructible_v<QState::ChildMode> && std::is_default_constructible_v<QState::ChildMode>) {
    if (signature == QLatin1String("setChildMode(QState::ChildMode)")) {
        if (args.size() != 1) { *error = QStringLiteral("setChildMode(QState::ChildMode) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QState::ChildMode>(), error);
            if (!converted0.isValid()) return true;
            QState::ChildMode arg0 = converted0.value<QState::ChildMode>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                target->setChildMode(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_29(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_30 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setDefaultState(QAbstractState*)")) {
        if (args.size() != 1) { *error = QStringLiteral("setDefaultState(QAbstractState*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractState*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractState* const arg0 = converted0.value<QAbstractState*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QHistoryState
        if (auto *target = dynamic_cast<QHistoryState *>(object); target != nullptr) {
                target->setDefaultState(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_30(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION)
    auto invoke_signature_31 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setDefaultTransition(QAbstractTransition*)")) {
        if (args.size() != 1) { *error = QStringLiteral("setDefaultTransition(QAbstractTransition*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractTransition*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractTransition* const arg0 = converted0.value<QAbstractTransition*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QHistoryState
        if (auto *target = dynamic_cast<QHistoryState *>(object); target != nullptr) {
                target->setDefaultTransition(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_31(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_32 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setErrorState(QAbstractState*)")) {
        if (args.size() != 1) { *error = QStringLiteral("setErrorState(QAbstractState*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractState*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractState* const arg0 = converted0.value<QAbstractState*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                target->setErrorState(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_32(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
    auto invoke_signature_33 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setEventSource(QObject*)")) {
        if (args.size() != 1) { *error = QStringLiteral("setEventSource(QObject*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QObject*>(), error);
            if (!converted0.isValid()) return true;
            QObject* const arg0 = converted0.value<QObject*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QEventTransition
        if (auto *target = dynamic_cast<QEventTransition *>(object); target != nullptr) {
                target->setEventSource(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_33(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QEVENT)
    auto invoke_signature_34 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QEvent::Type>::Defined && std::is_copy_constructible_v<QEvent::Type> && std::is_default_constructible_v<QEvent::Type>) {
    if (signature == QLatin1String("setEventType(QEvent::Type)")) {
        if (args.size() != 1) { *error = QStringLiteral("setEventType(QEvent::Type) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QEvent::Type>(), error);
            if (!converted0.isValid()) return true;
            QEvent::Type arg0 = converted0.value<QEvent::Type>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QEventTransition
        if (auto *target = dynamic_cast<QEventTransition *>(object); target != nullptr) {
                target->setEventType(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_34(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATE)
    auto invoke_signature_35 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QState::RestorePolicy>::Defined && std::is_copy_constructible_v<QState::RestorePolicy> && std::is_default_constructible_v<QState::RestorePolicy>) {
    if (signature == QLatin1String("setGlobalRestorePolicy(QState::RestorePolicy)")) {
        if (args.size() != 1) { *error = QStringLiteral("setGlobalRestorePolicy(QState::RestorePolicy) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QState::RestorePolicy>(), error);
            if (!converted0.isValid()) return true;
            QState::RestorePolicy arg0 = converted0.value<QState::RestorePolicy>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                target->setGlobalRestorePolicy(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_35(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QHISTORYSTATE)
    auto invoke_signature_36 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QHistoryState::HistoryType>::Defined && std::is_copy_constructible_v<QHistoryState::HistoryType> && std::is_default_constructible_v<QHistoryState::HistoryType>) {
    if (signature == QLatin1String("setHistoryType(QHistoryState::HistoryType)")) {
        if (args.size() != 1) { *error = QStringLiteral("setHistoryType(QHistoryState::HistoryType) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QHistoryState::HistoryType>(), error);
            if (!converted0.isValid()) return true;
            QHistoryState::HistoryType arg0 = converted0.value<QHistoryState::HistoryType>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QHistoryState
        if (auto *target = dynamic_cast<QHistoryState *>(object); target != nullptr) {
                target->setHistoryType(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_36(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPAINTERPATH)
    auto invoke_signature_37 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QPainterPath>::Defined && std::is_copy_constructible_v<QPainterPath> && std::is_default_constructible_v<QPainterPath>) {
    if (signature == QLatin1String("setHitTestPath(QPainterPath)")) {
        if (args.size() != 1) { *error = QStringLiteral("setHitTestPath(QPainterPath) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QPainterPath>(), error);
            if (!converted0.isValid()) return true;
            const QPainterPath arg0 = converted0.value<QPainterPath>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QMouseEventTransition
        if (auto *target = dynamic_cast<QMouseEventTransition *>(object); target != nullptr) {
                target->setHitTestPath(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_37(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_38 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setInitialState(QAbstractState*)")) {
        if (args.size() != 1) { *error = QStringLiteral("setInitialState(QAbstractState*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractState*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractState* const arg0 = converted0.value<QAbstractState*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                target->setInitialState(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_38(std::true_type{})) return true;
#endif
    auto invoke_signature_39 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setKey(int)")) {
        if (args.size() != 1) { *error = QStringLiteral("setKey(int) expects 1 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QKeyEventTransition
        if (auto *target = dynamic_cast<QKeyEventTransition *>(object); target != nullptr) {
                target->setKey(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_39(std::true_type{})) return true;
    auto invoke_signature_40 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setRunning(bool)")) {
        if (args.size() != 1) { *error = QStringLiteral("setRunning(bool) expects 1 argument(s)"); return true; }
            if (!args.at(0).isBool()) { *error = QStringLiteral("argument 0 must be a boolean"); return true; }
            const bool arg0 = args.at(0).toBool();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                target->setRunning(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_40(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
    auto invoke_signature_41 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setSenderObject(QObject*)")) {
        if (args.size() != 1) { *error = QStringLiteral("setSenderObject(QObject*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QObject*>(), error);
            if (!converted0.isValid()) return true;
            QObject* const arg0 = converted0.value<QObject*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QSignalTransition
        if (auto *target = dynamic_cast<QSignalTransition *>(object); target != nullptr) {
                target->setSenderObject(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_41(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
    auto invoke_signature_42 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QByteArray>::Defined && std::is_copy_constructible_v<QByteArray> && std::is_default_constructible_v<QByteArray>) {
    if (signature == QLatin1String("setSignal(QByteArray)")) {
        if (args.size() != 1) { *error = QStringLiteral("setSignal(QByteArray) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QByteArray>(), error);
            if (!converted0.isValid()) return true;
            const QByteArray arg0 = converted0.value<QByteArray>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QSignalTransition
        if (auto *target = dynamic_cast<QSignalTransition *>(object); target != nullptr) {
                target->setSignal(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_42(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_43 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setTargetState(QAbstractState*)")) {
        if (args.size() != 1) { *error = QStringLiteral("setTargetState(QAbstractState*) expects 1 argument(s)"); return true; }
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractState*>(), error);
            if (!converted0.isValid()) return true;
            QAbstractState* const arg0 = converted0.value<QAbstractState*>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractTransition
        if (auto *target = dynamic_cast<QAbstractTransition *>(object); target != nullptr) {
                target->setTargetState(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_43(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_44 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setTargetStates(QList<QAbstractState*>)")) {
        if (args.size() != 1) { *error = QStringLiteral("setTargetStates(QList<QAbstractState*>) expects 1 argument(s)"); return true; }
            if (!args.at(0).isArray()) { *error = QStringLiteral("argument 0 must be an array"); return true; }
            QList<QAbstractState*> arg0;
            for (const QJsonValue &entry : args.at(0).toArray()) {
                const QVariant converted = kry_qt6_direct::fromJson(entry, QMetaType::fromType<QAbstractState*>(), error);
                if (!converted.isValid()) return true;
                arg0.append(converted.value<QAbstractState*>());
            }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractTransition
        if (auto *target = dynamic_cast<QAbstractTransition *>(object); target != nullptr) {
                target->setTargetStates(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_44(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION)
    auto invoke_signature_45 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QAbstractTransition::TransitionType>::Defined && std::is_copy_constructible_v<QAbstractTransition::TransitionType> && std::is_default_constructible_v<QAbstractTransition::TransitionType>) {
    if (signature == QLatin1String("setTransitionType(QAbstractTransition::TransitionType)")) {
        if (args.size() != 1) { *error = QStringLiteral("setTransitionType(QAbstractTransition::TransitionType) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QAbstractTransition::TransitionType>(), error);
            if (!converted0.isValid()) return true;
            QAbstractTransition::TransitionType arg0 = converted0.value<QAbstractTransition::TransitionType>();
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractTransition
        if (auto *target = dynamic_cast<QAbstractTransition *>(object); target != nullptr) {
                target->setTransitionType(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_45(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
    auto invoke_signature_46 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("signal()")) {
        if (args.size() != 0) { *error = QStringLiteral("signal() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QSignalTransition
        if (auto *target = dynamic_cast<QSignalTransition *>(object); target != nullptr) {
                const QVariant convertedResult = kry_qt6_direct::storeValue<QByteArray>(target->signal());
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_46(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QSTATE)
    auto invoke_signature_47 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("sourceState()")) {
        if (args.size() != 0) { *error = QStringLiteral("sourceState() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractTransition
        if (auto *target = dynamic_cast<QAbstractTransition *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->sourceState())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_47(std::true_type{})) return true;
#endif
    auto invoke_signature_48 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("start()")) {
        if (args.size() != 0) { *error = QStringLiteral("start() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                target->start();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_48(std::true_type{})) return true;
    auto invoke_signature_49 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("stop()")) {
        if (args.size() != 0) { *error = QStringLiteral("stop() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QStateMachine
        if (auto *target = dynamic_cast<QStateMachine *>(object); target != nullptr) {
                target->stop();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_49(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_50 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("targetState()")) {
        if (args.size() != 0) { *error = QStringLiteral("targetState() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractTransition
        if (auto *target = dynamic_cast<QAbstractTransition *>(object); target != nullptr) {
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->targetState())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_50(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTSTATE)
    auto invoke_signature_51 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("targetStates()")) {
        if (args.size() != 0) { *error = QStringLiteral("targetStates() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractTransition
        if (auto *target = dynamic_cast<QAbstractTransition *>(object); target != nullptr) {
                QJsonArray values;
                for (const auto &item : target->targetStates()) {
                    values.append(kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(item))));
                }
                *output = values;
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_51(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION)
    auto invoke_signature_52 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("transitionType()")) {
        if (args.size() != 0) { *error = QStringLiteral("transitionType() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QAbstractTransition
        if (auto *target = dynamic_cast<QAbstractTransition *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QAbstractTransition::TransitionType>(target->transitionType()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_52(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTSTATEMACHINE_QABSTRACTTRANSITION)
    auto invoke_signature_53 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("transitions()")) {
        if (args.size() != 0) { *error = QStringLiteral("transitions() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTSTATEMACHINE_QState
        if (auto *target = dynamic_cast<QState *>(object); target != nullptr) {
                QJsonArray values;
                for (const auto &item : target->transitions()) {
                    values.append(kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(item))));
                }
                *output = values;
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_53(std::true_type{})) return true;
#endif
    return false;
}
} // namespace kry_qt6_direct
