// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QMetaType>
#include <QtCore/QObject>
#include <QtCore/QVariant>
#include <QtCore/QString>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QHash>
#include <QtCore/QStringList>
#include <type_traits>
#include <cmath>
#include <limits>

#if __has_include(<QtNfc/QNdefMessage>)
#include <QtNfc/QNdefMessage>
#define KRY_QT6_NATIVE_METHODS_QTNFC_QNdefMessage 1
#endif
#if __has_include(<QtNfc/QNearFieldManager>)
#include <QtNfc/QNearFieldManager>
#define KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldManager 1
#endif
#if __has_include(<QtNfc/QNearFieldTarget>)
#include <QtNfc/QNearFieldTarget>
#define KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget 1
#endif
#if __has_include(<QtNfc/QNearFieldTarget>)
#include <QtNfc/QNearFieldTarget>
#define KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET 1
#endif
#if __has_include(<QtCore/QByteArray>)
#include <QtCore/QByteArray>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY 1
#endif
#if __has_include(<QtNfc/QNdefMessage>)
#include <QtNfc/QNdefMessage>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTNFC_QNDEFMESSAGE 1
#endif

namespace kry_qt6_direct {
bool invoke_qtnfc_0(QObject *object, const QString &className, const QString &signature, const QJsonArray &args, QJsonValue *output, QString *error) {
#if defined(KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET)
    auto invoke_signature_0 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("accessMethods()")) {
        if (args.size() != 0) { *error = QStringLiteral("accessMethods() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QNearFieldTarget::AccessMethods>(target->accessMethods()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_0(std::true_type{})) return true;
#endif
    auto invoke_signature_1 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("disconnect()")) {
        if (args.size() != 0) { *error = QStringLiteral("disconnect() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->disconnect()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_1(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNFC_QNDEFMESSAGE)
    auto invoke_signature_2 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QByteArray>::Defined && std::is_copy_constructible_v<QByteArray> && std::is_default_constructible_v<QByteArray>) {
    if (signature == QLatin1String("fromByteArray(QByteArray)")) {
        if (args.size() != 1) { *error = QStringLiteral("fromByteArray(QByteArray) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QByteArray>(), error);
            if (!converted0.isValid()) return true;
            const QByteArray arg0 = converted0.value<QByteArray>();
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNdefMessage
        if (className == QLatin1String("QtNfc.QNdefMessage")) {
                const QVariant convertedResult = kry_qt6_direct::storeValue<QNdefMessage>(QNdefMessage::fromByteArray(arg0));
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_2(std::true_type{})) return true;
#endif
    auto invoke_signature_3 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("hasNdefMessage()")) {
        if (args.size() != 0) { *error = QStringLiteral("hasNdefMessage() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->hasNdefMessage()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_3(std::true_type{})) return true;
    auto invoke_signature_4 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("isEnabled()")) {
        if (args.size() != 0) { *error = QStringLiteral("isEnabled() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldManager
        if (auto *target = dynamic_cast<QNearFieldManager *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->isEnabled()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_4(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET)
    auto invoke_signature_5 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QNearFieldTarget::AccessMethod>::Defined && std::is_copy_constructible_v<QNearFieldTarget::AccessMethod> && std::is_default_constructible_v<QNearFieldTarget::AccessMethod>) {
    if (signature == QLatin1String("isSupported(QNearFieldTarget::AccessMethod)")) {
        if (args.size() != 1) { *error = QStringLiteral("isSupported(QNearFieldTarget::AccessMethod) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNearFieldTarget::AccessMethod>(), error);
            if (!converted0.isValid()) return true;
            QNearFieldTarget::AccessMethod arg0 = converted0.value<QNearFieldTarget::AccessMethod>();
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldManager
        if (auto *target = dynamic_cast<QNearFieldManager *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->isSupported(arg0)));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_5(std::true_type{})) return true;
#endif
    auto invoke_signature_6 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("maxCommandLength()")) {
        if (args.size() != 0) { *error = QStringLiteral("maxCommandLength() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<double>(target->maxCommandLength()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_6(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET)
    auto invoke_signature_7 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("readNdefMessages()")) {
        if (args.size() != 0) { *error = QStringLiteral("readNdefMessages() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QNearFieldTarget::RequestId>(target->readNdefMessages()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_7(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET)
    auto invoke_signature_8 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QNearFieldTarget::RequestId>::Defined && std::is_copy_constructible_v<QNearFieldTarget::RequestId> && std::is_default_constructible_v<QNearFieldTarget::RequestId>) {
    if (signature == QLatin1String("requestResponse(QNearFieldTarget::RequestId)")) {
        if (args.size() != 1) { *error = QStringLiteral("requestResponse(QNearFieldTarget::RequestId) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNearFieldTarget::RequestId>(), error);
            if (!converted0.isValid()) return true;
            QNearFieldTarget::RequestId arg0 = converted0.value<QNearFieldTarget::RequestId>();
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(target->requestResponse(arg0));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_8(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
    auto invoke_signature_9 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QByteArray>::Defined && std::is_copy_constructible_v<QByteArray> && std::is_default_constructible_v<QByteArray>) {
    if (signature == QLatin1String("sendCommand(QByteArray)")) {
        if (args.size() != 1) { *error = QStringLiteral("sendCommand(QByteArray) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QByteArray>(), error);
            if (!converted0.isValid()) return true;
            const QByteArray arg0 = converted0.value<QByteArray>();
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QNearFieldTarget::RequestId>(target->sendCommand(arg0)));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_9(std::true_type{})) return true;
#endif
    auto invoke_signature_10 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setUserInformation(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("setUserInformation(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldManager
        if (auto *target = dynamic_cast<QNearFieldManager *>(object); target != nullptr) {
                target->setUserInformation(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_10(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET)
    auto invoke_signature_11 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QNearFieldTarget::AccessMethod>::Defined && std::is_copy_constructible_v<QNearFieldTarget::AccessMethod> && std::is_default_constructible_v<QNearFieldTarget::AccessMethod>) {
    if (signature == QLatin1String("startTargetDetection(QNearFieldTarget::AccessMethod)")) {
        if (args.size() != 1) { *error = QStringLiteral("startTargetDetection(QNearFieldTarget::AccessMethod) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNearFieldTarget::AccessMethod>(), error);
            if (!converted0.isValid()) return true;
            QNearFieldTarget::AccessMethod arg0 = converted0.value<QNearFieldTarget::AccessMethod>();
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldManager
        if (auto *target = dynamic_cast<QNearFieldManager *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->startTargetDetection(arg0)));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_11(std::true_type{})) return true;
#endif
    auto invoke_signature_12 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("stopTargetDetection(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("stopTargetDetection(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldManager
        if (auto *target = dynamic_cast<QNearFieldManager *>(object); target != nullptr) {
                target->stopTargetDetection(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_12(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET)
    auto invoke_signature_13 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("type()")) {
        if (args.size() != 0) { *error = QStringLiteral("type() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QNearFieldTarget::Type>(target->type()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_13(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QBYTEARRAY)
    auto invoke_signature_14 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("uid()")) {
        if (args.size() != 0) { *error = QStringLiteral("uid() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                const QVariant convertedResult = kry_qt6_direct::storeValue<QByteArray>(target->uid());
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_14(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET)
    auto invoke_signature_15 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QNearFieldTarget::RequestId>::Defined && std::is_copy_constructible_v<QNearFieldTarget::RequestId> && std::is_default_constructible_v<QNearFieldTarget::RequestId>) {
    if (signature == QLatin1String("waitForRequestCompleted(QNearFieldTarget::RequestId,int)")) {
        if (args.size() != 2) { *error = QStringLiteral("waitForRequestCompleted(QNearFieldTarget::RequestId,int) expects 2 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNearFieldTarget::RequestId>(), error);
            if (!converted0.isValid()) return true;
            QNearFieldTarget::RequestId arg0 = converted0.value<QNearFieldTarget::RequestId>();
            int arg1 = 0;
            if (!args.at(1).isDouble() || !std::isfinite(args.at(1).toDouble()) || std::floor(args.at(1).toDouble()) != args.at(1).toDouble() || args.at(1).toDouble() < std::numeric_limits<int>::min() || args.at(1).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 1 must be a 32-bit integer"); return true; }
            arg1 = static_cast<int>(args.at(1).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = QJsonValue(static_cast<bool>(target->waitForRequestCompleted(arg0, arg1)));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_15(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTNFC_QNEARFIELDTARGET) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTNFC_QNDEFMESSAGE)
    auto invoke_signature_16 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QNdefMessage>::Defined && std::is_copy_constructible_v<QNdefMessage> && std::is_default_constructible_v<QNdefMessage>) {
    if (signature == QLatin1String("writeNdefMessages(QList<QNdefMessage>)")) {
        if (args.size() != 1) { *error = QStringLiteral("writeNdefMessages(QList<QNdefMessage>) expects 1 argument(s)"); return true; }
            if (!args.at(0).isArray()) { *error = QStringLiteral("argument 0 must be an array"); return true; }
            QList<QNdefMessage> arg0;
            for (const QJsonValue &entry : args.at(0).toArray()) {
                const QVariant converted = kry_qt6_direct::fromJson(entry, QMetaType::fromType<QNdefMessage>(), error);
                if (!converted.isValid()) return true;
                arg0.append(converted.value<QNdefMessage>());
            }
#ifdef KRY_QT6_NATIVE_METHODS_QTNFC_QNearFieldTarget
        if (auto *target = dynamic_cast<QNearFieldTarget *>(object); target != nullptr) {
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QNearFieldTarget::RequestId>(target->writeNdefMessages(arg0)));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_16(std::true_type{})) return true;
#endif
    return false;
}
} // namespace kry_qt6_direct
