// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QMetaType>
#include <QtCore/QObject>
#include <QtCore/QVariant>
#include <QtCore/QString>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QHash>
#include <QtCore/QStringList>
#include <type_traits>
#include <cmath>
#include <limits>

#if __has_include(<QtCore/QModelRoleData>)
#include <QtCore/QModelRoleData>
#define KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleData 1
#endif
#if __has_include(<QtCore/QModelRoleDataSpan>)
#include <QtCore/QModelRoleDataSpan>
#define KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleDataSpan 1
#endif
#if __has_include(<QtCore/QMutex>)
#include <QtCore/QMutex>
#define KRY_QT6_NATIVE_METHODS_QTCORE_QMutex 1
#endif
#if __has_include(<QtCore/QNativeIpcKey>)
#include <QtCore/QNativeIpcKey>
#define KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey 1
#endif
#if __has_include(<QtCore/QOperatingSystemVersion>)
#include <QtCore/QOperatingSystemVersion>
#define KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersion 1
#endif
#if __has_include(<QtCore/QOperatingSystemVersionBase>)
#include <QtCore/QOperatingSystemVersionBase>
#define KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersionBase 1
#endif
#if __has_include(<QtCore/QPermission>)
#include <QtCore/QPermission>
#define KRY_QT6_NATIVE_METHODS_QTCORE_QPermission 1
#endif
#if __has_include(<QtCore/QPersistentModelIndex>)
#include <QtCore/QPersistentModelIndex>
#define KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex 1
#endif
#if __has_include(<QtCore/QAbstractItemModel>)
#include <QtCore/QAbstractItemModel>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QABSTRACTITEMMODEL 1
#endif
#include <QtCore/Qt>
#define KRY_QT6_NATIVE_ENUM_QT_PERMISSIONSTATUS 1
#if __has_include(<QtCore/QNativeIpcKey>)
#include <QtCore/QNativeIpcKey>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QNATIVEIPCKEY 1
#endif
#if __has_include(<QtCore/QOperatingSystemVersion>)
#include <QtCore/QOperatingSystemVersion>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QOPERATINGSYSTEMVERSION 1
#endif
#if __has_include(<QtCore/QDeadlineTimer>)
#include <QtCore/QDeadlineTimer>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QDEADLINETIMER 1
#endif
#if __has_include(<QtCore/QMetaType>)
#include <QtCore/QMetaType>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QMETATYPE 1
#endif
#if __has_include(<QtCore/QModelIndex>)
#include <QtCore/QModelIndex>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QMODELINDEX 1
#endif
#if __has_include(<QtCore/QNativeIpcKey>)
#include <QtCore/QNativeIpcKey>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QNATIVEIPCKEY 1
#endif
#if __has_include(<QtCore/QPersistentModelIndex>)
#include <QtCore/QPersistentModelIndex>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPERSISTENTMODELINDEX 1
#endif
#if __has_include(<QtCore/QVersionNumber>)
#include <QtCore/QVersionNumber>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QVERSIONNUMBER 1
#endif

namespace kry_qt6_direct {
bool invoke_value_qtcore_6(QVariant *value, const QString &className, const QString &signature, const QJsonArray &args, QJsonValue *output, QString *error) {
    auto invoke_signature_0 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("clearData()")) {
        if (args.size() != 0) { *error = QStringLiteral("clearData() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleData
        if (className == QLatin1String("QModelRoleData") && value != nullptr && value->metaType() == QMetaType::fromType<QModelRoleData>()) {
            auto *target = static_cast<QModelRoleData *>(value->data());
                target->clearData();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_0(std::true_type{})) return true;
    auto invoke_signature_1 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("column()")) {
        if (args.size() != 0) { *error = QStringLiteral("column() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex
        if (className == QLatin1String("QPersistentModelIndex") && value != nullptr && value->metaType() == QMetaType::fromType<QPersistentModelIndex>()) {
            auto *target = static_cast<QPersistentModelIndex *>(value->data());
                *output = QJsonValue(static_cast<double>(target->column()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_1(std::true_type{})) return true;
    auto invoke_signature_2 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("data()")) {
        if (args.size() != 0) { *error = QStringLiteral("data() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleData
        if (className == QLatin1String("QModelRoleData") && value != nullptr && value->metaType() == QMetaType::fromType<QModelRoleData>()) {
            auto *target = static_cast<QModelRoleData *>(value->data());
                *output = kry_qt6_direct::toJson(target->data());
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_2(std::true_type{})) return true;
    auto invoke_signature_3 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("data(int)")) {
        if (args.size() != 1) { *error = QStringLiteral("data(int) expects 1 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex
        if (className == QLatin1String("QPersistentModelIndex") && value != nullptr && value->metaType() == QMetaType::fromType<QPersistentModelIndex>()) {
            auto *target = static_cast<QPersistentModelIndex *>(value->data());
                *output = kry_qt6_direct::toJson(target->data(arg0));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_3(std::true_type{})) return true;
    auto invoke_signature_4 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("isEmpty()")) {
        if (args.size() != 0) { *error = QStringLiteral("isEmpty() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey
        if (className == QLatin1String("QNativeIpcKey") && value != nullptr && value->metaType() == QMetaType::fromType<QNativeIpcKey>()) {
            auto *target = static_cast<QNativeIpcKey *>(value->data());
                *output = QJsonValue(static_cast<bool>(target->isEmpty()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_4(std::true_type{})) return true;
    auto invoke_signature_5 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("isValid()")) {
        if (args.size() != 0) { *error = QStringLiteral("isValid() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey
        if (className == QLatin1String("QNativeIpcKey") && value != nullptr && value->metaType() == QMetaType::fromType<QNativeIpcKey>()) {
            auto *target = static_cast<QNativeIpcKey *>(value->data());
                *output = QJsonValue(static_cast<bool>(target->isValid()));
            return true;
        }
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex
        if (className == QLatin1String("QPersistentModelIndex") && value != nullptr && value->metaType() == QMetaType::fromType<QPersistentModelIndex>()) {
            auto *target = static_cast<QPersistentModelIndex *>(value->data());
                *output = QJsonValue(static_cast<bool>(target->isValid()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_5(std::true_type{})) return true;
    auto invoke_signature_6 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("length()")) {
        if (args.size() != 0) { *error = QStringLiteral("length() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleDataSpan
        if (className == QLatin1String("QModelRoleDataSpan") && value != nullptr && value->metaType() == QMetaType::fromType<QModelRoleDataSpan>()) {
            auto *target = static_cast<QModelRoleDataSpan *>(value->data());
                *output = kry_qt6_direct::toJson(QVariant::fromValue<qsizetype>(target->length()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_6(std::true_type{})) return true;
    auto invoke_signature_7 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("lock()")) {
        if (args.size() != 0) { *error = QStringLiteral("lock() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QMutex
        if (className == QLatin1String("QMutex") && value != nullptr && value->metaType() == QMetaType::fromType<QMutex>()) {
            auto *target = static_cast<QMutex *>(value->data());
                target->lock();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_7(std::true_type{})) return true;
    auto invoke_signature_8 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("majorVersion()")) {
        if (args.size() != 0) { *error = QStringLiteral("majorVersion() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersionBase
        if (className == QLatin1String("QOperatingSystemVersionBase") && value != nullptr && value->metaType() == QMetaType::fromType<QOperatingSystemVersionBase>()) {
            auto *target = static_cast<QOperatingSystemVersionBase *>(value->data());
                *output = QJsonValue(static_cast<double>(target->majorVersion()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_8(std::true_type{})) return true;
    auto invoke_signature_9 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("microVersion()")) {
        if (args.size() != 0) { *error = QStringLiteral("microVersion() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersionBase
        if (className == QLatin1String("QOperatingSystemVersionBase") && value != nullptr && value->metaType() == QMetaType::fromType<QOperatingSystemVersionBase>()) {
            auto *target = static_cast<QOperatingSystemVersionBase *>(value->data());
                *output = QJsonValue(static_cast<double>(target->microVersion()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_9(std::true_type{})) return true;
    auto invoke_signature_10 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("minorVersion()")) {
        if (args.size() != 0) { *error = QStringLiteral("minorVersion() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersionBase
        if (className == QLatin1String("QOperatingSystemVersionBase") && value != nullptr && value->metaType() == QMetaType::fromType<QOperatingSystemVersionBase>()) {
            auto *target = static_cast<QOperatingSystemVersionBase *>(value->data());
                *output = QJsonValue(static_cast<double>(target->minorVersion()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_10(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QABSTRACTITEMMODEL)
    auto invoke_signature_11 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("model()")) {
        if (args.size() != 0) { *error = QStringLiteral("model() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex
        if (className == QLatin1String("QPersistentModelIndex") && value != nullptr && value->metaType() == QMetaType::fromType<QPersistentModelIndex>()) {
            auto *target = static_cast<QPersistentModelIndex *>(value->data());
                *output = kry_qt6_direct::objectHandle(const_cast<QObject *>(static_cast<const QObject *>(target->model())));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_11(std::true_type{})) return true;
#endif
    auto invoke_signature_12 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("name()")) {
        if (args.size() != 0) { *error = QStringLiteral("name() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersionBase
        if (className == QLatin1String("QOperatingSystemVersionBase") && value != nullptr && value->metaType() == QMetaType::fromType<QOperatingSystemVersionBase>()) {
            auto *target = static_cast<QOperatingSystemVersionBase *>(value->data());
                *output = QJsonValue(QString(target->name()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_12(std::true_type{})) return true;
    auto invoke_signature_13 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("nativeKey()")) {
        if (args.size() != 0) { *error = QStringLiteral("nativeKey() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey
        if (className == QLatin1String("QNativeIpcKey") && value != nullptr && value->metaType() == QMetaType::fromType<QNativeIpcKey>()) {
            auto *target = static_cast<QNativeIpcKey *>(value->data());
                *output = QJsonValue(QString(target->nativeKey()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_13(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QMODELINDEX)
    auto invoke_signature_14 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("parent()")) {
        if (args.size() != 0) { *error = QStringLiteral("parent() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex
        if (className == QLatin1String("QPersistentModelIndex") && value != nullptr && value->metaType() == QMetaType::fromType<QPersistentModelIndex>()) {
            auto *target = static_cast<QPersistentModelIndex *>(value->data());
                const QVariant convertedResult = kry_qt6_direct::storeValue<QModelIndex>(target->parent());
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_14(std::true_type{})) return true;
#endif
    auto invoke_signature_15 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("role()")) {
        if (args.size() != 0) { *error = QStringLiteral("role() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleData
        if (className == QLatin1String("QModelRoleData") && value != nullptr && value->metaType() == QMetaType::fromType<QModelRoleData>()) {
            auto *target = static_cast<QModelRoleData *>(value->data());
                *output = QJsonValue(static_cast<double>(target->role()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_15(std::true_type{})) return true;
    auto invoke_signature_16 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("row()")) {
        if (args.size() != 0) { *error = QStringLiteral("row() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex
        if (className == QLatin1String("QPersistentModelIndex") && value != nullptr && value->metaType() == QMetaType::fromType<QPersistentModelIndex>()) {
            auto *target = static_cast<QPersistentModelIndex *>(value->data());
                *output = QJsonValue(static_cast<double>(target->row()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_16(std::true_type{})) return true;
    auto invoke_signature_17 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("segmentCount()")) {
        if (args.size() != 0) { *error = QStringLiteral("segmentCount() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersionBase
        if (className == QLatin1String("QOperatingSystemVersionBase") && value != nullptr && value->metaType() == QMetaType::fromType<QOperatingSystemVersionBase>()) {
            auto *target = static_cast<QOperatingSystemVersionBase *>(value->data());
                *output = QJsonValue(static_cast<double>(target->segmentCount()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_17(std::true_type{})) return true;
    auto invoke_signature_18 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setData(QVariant)")) {
        if (args.size() != 1) { *error = QStringLiteral("setData(QVariant) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QVariant>(), error);
            const QVariant arg0 = converted0;
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleData
        if (className == QLatin1String("QModelRoleData") && value != nullptr && value->metaType() == QMetaType::fromType<QModelRoleData>()) {
            auto *target = static_cast<QModelRoleData *>(value->data());
                target->setData(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_18(std::true_type{})) return true;
    auto invoke_signature_19 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setNativeKey(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("setNativeKey(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey
        if (className == QLatin1String("QNativeIpcKey") && value != nullptr && value->metaType() == QMetaType::fromType<QNativeIpcKey>()) {
            auto *target = static_cast<QNativeIpcKey *>(value->data());
                target->setNativeKey(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_19(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QNATIVEIPCKEY)
    auto invoke_signature_20 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QNativeIpcKey::Type>::Defined && std::is_copy_constructible_v<QNativeIpcKey::Type> && std::is_default_constructible_v<QNativeIpcKey::Type>) {
    if (signature == QLatin1String("setType(QNativeIpcKey::Type)")) {
        if (args.size() != 1) { *error = QStringLiteral("setType(QNativeIpcKey::Type) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNativeIpcKey::Type>(), error);
            if (!converted0.isValid()) return true;
            QNativeIpcKey::Type arg0 = converted0.value<QNativeIpcKey::Type>();
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey
        if (className == QLatin1String("QNativeIpcKey") && value != nullptr && value->metaType() == QMetaType::fromType<QNativeIpcKey>()) {
            auto *target = static_cast<QNativeIpcKey *>(value->data());
                target->setType(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_20(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QMODELINDEX)
    auto invoke_signature_21 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("sibling(int,int)")) {
        if (args.size() != 2) { *error = QStringLiteral("sibling(int,int) expects 2 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
            int arg1 = 0;
            if (!args.at(1).isDouble() || !std::isfinite(args.at(1).toDouble()) || std::floor(args.at(1).toDouble()) != args.at(1).toDouble() || args.at(1).toDouble() < std::numeric_limits<int>::min() || args.at(1).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 1 must be a 32-bit integer"); return true; }
            arg1 = static_cast<int>(args.at(1).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex
        if (className == QLatin1String("QPersistentModelIndex") && value != nullptr && value->metaType() == QMetaType::fromType<QPersistentModelIndex>()) {
            auto *target = static_cast<QPersistentModelIndex *>(value->data());
                const QVariant convertedResult = kry_qt6_direct::storeValue<QModelIndex>(target->sibling(arg0, arg1));
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_21(std::true_type{})) return true;
#endif
    auto invoke_signature_22 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("size()")) {
        if (args.size() != 0) { *error = QStringLiteral("size() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleDataSpan
        if (className == QLatin1String("QModelRoleDataSpan") && value != nullptr && value->metaType() == QMetaType::fromType<QModelRoleDataSpan>()) {
            auto *target = static_cast<QModelRoleDataSpan *>(value->data());
                *output = kry_qt6_direct::toJson(QVariant::fromValue<qsizetype>(target->size()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_22(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_ENUM_QT_PERMISSIONSTATUS)
    auto invoke_signature_23 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("status()")) {
        if (args.size() != 0) { *error = QStringLiteral("status() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPermission
        if (className == QLatin1String("QPermission") && value != nullptr && value->metaType() == QMetaType::fromType<QPermission>()) {
            auto *target = static_cast<QPermission *>(value->data());
                *output = kry_qt6_direct::toJson(QVariant::fromValue<Qt::PermissionStatus>(target->status()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_23(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QNATIVEIPCKEY)
    auto invoke_signature_24 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QNativeIpcKey>::Defined && std::is_copy_constructible_v<QNativeIpcKey> && std::is_default_constructible_v<QNativeIpcKey>) {
    if (signature == QLatin1String("swap(QNativeIpcKey)")) {
        if (args.size() != 1) { *error = QStringLiteral("swap(QNativeIpcKey) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QNativeIpcKey>(), error);
            if (!converted0.isValid()) return true;
            QNativeIpcKey arg0 = converted0.value<QNativeIpcKey>();
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey
        if (className == QLatin1String("QNativeIpcKey") && value != nullptr && value->metaType() == QMetaType::fromType<QNativeIpcKey>()) {
            auto *target = static_cast<QNativeIpcKey *>(value->data());
                target->swap(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_24(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QPERSISTENTMODELINDEX)
    auto invoke_signature_25 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QPersistentModelIndex>::Defined && std::is_copy_constructible_v<QPersistentModelIndex> && std::is_default_constructible_v<QPersistentModelIndex>) {
    if (signature == QLatin1String("swap(QPersistentModelIndex)")) {
        if (args.size() != 1) { *error = QStringLiteral("swap(QPersistentModelIndex) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QPersistentModelIndex>(), error);
            if (!converted0.isValid()) return true;
            QPersistentModelIndex arg0 = converted0.value<QPersistentModelIndex>();
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex
        if (className == QLatin1String("QPersistentModelIndex") && value != nullptr && value->metaType() == QMetaType::fromType<QPersistentModelIndex>()) {
            auto *target = static_cast<QPersistentModelIndex *>(value->data());
                target->swap(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_25(std::true_type{})) return true;
#endif
    auto invoke_signature_26 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("toString()")) {
        if (args.size() != 0) { *error = QStringLiteral("toString() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey
        if (className == QLatin1String("QNativeIpcKey") && value != nullptr && value->metaType() == QMetaType::fromType<QNativeIpcKey>()) {
            auto *target = static_cast<QNativeIpcKey *>(value->data());
                *output = QJsonValue(QString(target->toString()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_26(std::true_type{})) return true;
    auto invoke_signature_27 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("tryLock()")) {
        if (args.size() != 0) { *error = QStringLiteral("tryLock() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QMutex
        if (className == QLatin1String("QMutex") && value != nullptr && value->metaType() == QMetaType::fromType<QMutex>()) {
            auto *target = static_cast<QMutex *>(value->data());
                *output = QJsonValue(static_cast<bool>(target->tryLock()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_27(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QDEADLINETIMER)
    auto invoke_signature_28 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QDeadlineTimer>::Defined && std::is_copy_constructible_v<QDeadlineTimer> && std::is_default_constructible_v<QDeadlineTimer>) {
    if (signature == QLatin1String("tryLock(QDeadlineTimer)")) {
        if (args.size() != 1) { *error = QStringLiteral("tryLock(QDeadlineTimer) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QDeadlineTimer>(), error);
            if (!converted0.isValid()) return true;
            const QDeadlineTimer arg0 = converted0.value<QDeadlineTimer>();
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QMutex
        if (className == QLatin1String("QMutex") && value != nullptr && value->metaType() == QMetaType::fromType<QMutex>()) {
            auto *target = static_cast<QMutex *>(value->data());
                *output = QJsonValue(static_cast<bool>(target->tryLock(arg0)));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_28(std::true_type{})) return true;
#endif
    auto invoke_signature_29 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("tryLock(int)")) {
        if (args.size() != 1) { *error = QStringLiteral("tryLock(int) expects 1 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QMutex
        if (className == QLatin1String("QMutex") && value != nullptr && value->metaType() == QMetaType::fromType<QMutex>()) {
            auto *target = static_cast<QMutex *>(value->data());
                *output = QJsonValue(static_cast<bool>(target->tryLock(arg0)));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_29(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QMETATYPE)
    auto invoke_signature_30 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("type()")) {
        if (args.size() != 0) { *error = QStringLiteral("type() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPermission
        if (className == QLatin1String("QPermission") && value != nullptr && value->metaType() == QMetaType::fromType<QPermission>()) {
            auto *target = static_cast<QPermission *>(value->data());
                const QVariant convertedResult = kry_qt6_direct::storeValue<QMetaType>(target->type());
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_30(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QNATIVEIPCKEY)
    auto invoke_signature_31 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("type()")) {
        if (args.size() != 0) { *error = QStringLiteral("type() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey
        if (className == QLatin1String("QNativeIpcKey") && value != nullptr && value->metaType() == QMetaType::fromType<QNativeIpcKey>()) {
            auto *target = static_cast<QNativeIpcKey *>(value->data());
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QNativeIpcKey::Type>(target->type()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_31(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOPERATINGSYSTEMVERSION)
    auto invoke_signature_32 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("type()")) {
        if (args.size() != 0) { *error = QStringLiteral("type() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersion
        if (className == QLatin1String("QOperatingSystemVersion") && value != nullptr && value->metaType() == QMetaType::fromType<QOperatingSystemVersion>()) {
            auto *target = static_cast<QOperatingSystemVersion *>(value->data());
                *output = kry_qt6_direct::toJson(QVariant::fromValue<QOperatingSystemVersion::OSType>(target->type()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_32(std::true_type{})) return true;
#endif
    auto invoke_signature_33 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("unlock()")) {
        if (args.size() != 0) { *error = QStringLiteral("unlock() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QMutex
        if (className == QLatin1String("QMutex") && value != nullptr && value->metaType() == QMetaType::fromType<QMutex>()) {
            auto *target = static_cast<QMutex *>(value->data());
                target->unlock();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_33(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QVERSIONNUMBER)
    auto invoke_signature_34 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("version()")) {
        if (args.size() != 0) { *error = QStringLiteral("version() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersionBase
        if (className == QLatin1String("QOperatingSystemVersionBase") && value != nullptr && value->metaType() == QMetaType::fromType<QOperatingSystemVersionBase>()) {
            auto *target = static_cast<QOperatingSystemVersionBase *>(value->data());
                const QVariant convertedResult = kry_qt6_direct::storeValue<QVersionNumber>(target->version());
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_34(std::true_type{})) return true;
#endif
    return false;
}
QStringList direct_value_types_qtcore_6() {
    QStringList result;
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleData
    if (QMetaTypeId2<QModelRoleData>::Defined && std::is_copy_constructible_v<QModelRoleData>) result.append(QStringLiteral("QModelRoleData"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QModelRoleDataSpan
    if (QMetaTypeId2<QModelRoleDataSpan>::Defined && std::is_copy_constructible_v<QModelRoleDataSpan>) result.append(QStringLiteral("QModelRoleDataSpan"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QMutex
    if (QMetaTypeId2<QMutex>::Defined && std::is_copy_constructible_v<QMutex>) result.append(QStringLiteral("QMutex"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QNativeIpcKey
    if (QMetaTypeId2<QNativeIpcKey>::Defined && std::is_copy_constructible_v<QNativeIpcKey>) result.append(QStringLiteral("QNativeIpcKey"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersion
    if (QMetaTypeId2<QOperatingSystemVersion>::Defined && std::is_copy_constructible_v<QOperatingSystemVersion>) result.append(QStringLiteral("QOperatingSystemVersion"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QOperatingSystemVersionBase
    if (QMetaTypeId2<QOperatingSystemVersionBase>::Defined && std::is_copy_constructible_v<QOperatingSystemVersionBase>) result.append(QStringLiteral("QOperatingSystemVersionBase"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPermission
    if (QMetaTypeId2<QPermission>::Defined && std::is_copy_constructible_v<QPermission>) result.append(QStringLiteral("QPermission"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QTCORE_QPersistentModelIndex
    if (QMetaTypeId2<QPersistentModelIndex>::Defined && std::is_copy_constructible_v<QPersistentModelIndex>) result.append(QStringLiteral("QPersistentModelIndex"));
#endif
    return result;
}
} // namespace kry_qt6_direct
