// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QMetaType>
#include <QtCore/QObject>
#include <QtCore/QVariant>
#include <QtCore/QString>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QHash>
#include <QtCore/QStringList>
#include <type_traits>
#include <cmath>
#include <limits>

#if __has_include(<Qt3DAnimation/QAnimationClipData>)
#include <Qt3DAnimation/QAnimationClipData>
#define KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QAnimationClipData 1
#endif
#if __has_include(<Qt3DAnimation/QChannel>)
#include <Qt3DAnimation/QChannel>
#define KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannel 1
#endif
#if __has_include(<Qt3DAnimation/QChannelComponent>)
#include <Qt3DAnimation/QChannelComponent>
#define KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannelComponent 1
#endif
#if __has_include(<Qt3DAnimation/QKeyFrame>)
#include <Qt3DAnimation/QKeyFrame>
#define KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame 1
#endif
#if __has_include(<Qt3DAnimation/QKeyFrame>)
#include <Qt3DAnimation/QKeyFrame>
#define KRY_QT6_NATIVE_TYPE_QT3DANIMATION_QKEYFRAME 1
#endif
#if __has_include(<QtGui/QVector2D>)
#include <QtGui/QVector2D>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QVECTOR2D 1
#endif

namespace kry_qt6_direct {
bool invoke_value_qt3danimation_0(QVariant *value, const QString &className, const QString &signature, const QJsonArray &args, QJsonValue *output, QString *error) {
    auto invoke_signature_0 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("channelComponentCount()")) {
        if (args.size() != 0) { *error = QStringLiteral("channelComponentCount() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannel
        if (className == QLatin1String("QChannel") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannel>()) {
            auto *target = static_cast<Qt3DAnimation::QChannel *>(value->data());
                *output = QJsonValue(static_cast<double>(target->channelComponentCount()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_0(std::true_type{})) return true;
    auto invoke_signature_1 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("channelCount()")) {
        if (args.size() != 0) { *error = QStringLiteral("channelCount() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QAnimationClipData
        if (className == QLatin1String("QAnimationClipData") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QAnimationClipData>()) {
            auto *target = static_cast<Qt3DAnimation::QAnimationClipData *>(value->data());
                *output = QJsonValue(static_cast<double>(target->channelCount()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_1(std::true_type{})) return true;
    auto invoke_signature_2 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("clearChannelComponents()")) {
        if (args.size() != 0) { *error = QStringLiteral("clearChannelComponents() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannel
        if (className == QLatin1String("QChannel") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannel>()) {
            auto *target = static_cast<Qt3DAnimation::QChannel *>(value->data());
                target->clearChannelComponents();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_2(std::true_type{})) return true;
    auto invoke_signature_3 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("clearChannels()")) {
        if (args.size() != 0) { *error = QStringLiteral("clearChannels() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QAnimationClipData
        if (className == QLatin1String("QAnimationClipData") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QAnimationClipData>()) {
            auto *target = static_cast<Qt3DAnimation::QAnimationClipData *>(value->data());
                target->clearChannels();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_3(std::true_type{})) return true;
    auto invoke_signature_4 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("clearKeyFrames()")) {
        if (args.size() != 0) { *error = QStringLiteral("clearKeyFrames() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannelComponent
        if (className == QLatin1String("QChannelComponent") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannelComponent>()) {
            auto *target = static_cast<Qt3DAnimation::QChannelComponent *>(value->data());
                target->clearKeyFrames();
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_4(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QVECTOR2D)
    auto invoke_signature_5 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("coordinates()")) {
        if (args.size() != 0) { *error = QStringLiteral("coordinates() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame
        if (className == QLatin1String("QKeyFrame") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QKeyFrame>()) {
            auto *target = static_cast<Qt3DAnimation::QKeyFrame *>(value->data());
                const QVariant convertedResult = kry_qt6_direct::storeValue<QVector2D>(target->coordinates());
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_5(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QT3DANIMATION_QKEYFRAME)
    auto invoke_signature_6 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("interpolationType()")) {
        if (args.size() != 0) { *error = QStringLiteral("interpolationType() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame
        if (className == QLatin1String("QKeyFrame") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QKeyFrame>()) {
            auto *target = static_cast<Qt3DAnimation::QKeyFrame *>(value->data());
                *output = kry_qt6_direct::toJson(QVariant::fromValue<Qt3DAnimation::QKeyFrame::InterpolationType>(target->interpolationType()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_6(std::true_type{})) return true;
#endif
    auto invoke_signature_7 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("isValid()")) {
        if (args.size() != 0) { *error = QStringLiteral("isValid() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QAnimationClipData
        if (className == QLatin1String("QAnimationClipData") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QAnimationClipData>()) {
            auto *target = static_cast<Qt3DAnimation::QAnimationClipData *>(value->data());
                *output = QJsonValue(static_cast<bool>(target->isValid()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_7(std::true_type{})) return true;
    auto invoke_signature_8 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("jointIndex()")) {
        if (args.size() != 0) { *error = QStringLiteral("jointIndex() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannel
        if (className == QLatin1String("QChannel") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannel>()) {
            auto *target = static_cast<Qt3DAnimation::QChannel *>(value->data());
                *output = QJsonValue(static_cast<double>(target->jointIndex()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_8(std::true_type{})) return true;
    auto invoke_signature_9 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("keyFrameCount()")) {
        if (args.size() != 0) { *error = QStringLiteral("keyFrameCount() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannelComponent
        if (className == QLatin1String("QChannelComponent") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannelComponent>()) {
            auto *target = static_cast<Qt3DAnimation::QChannelComponent *>(value->data());
                *output = QJsonValue(static_cast<double>(target->keyFrameCount()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_9(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QVECTOR2D)
    auto invoke_signature_10 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("leftControlPoint()")) {
        if (args.size() != 0) { *error = QStringLiteral("leftControlPoint() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame
        if (className == QLatin1String("QKeyFrame") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QKeyFrame>()) {
            auto *target = static_cast<Qt3DAnimation::QKeyFrame *>(value->data());
                const QVariant convertedResult = kry_qt6_direct::storeValue<QVector2D>(target->leftControlPoint());
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_10(std::true_type{})) return true;
#endif
    auto invoke_signature_11 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("name()")) {
        if (args.size() != 0) { *error = QStringLiteral("name() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QAnimationClipData
        if (className == QLatin1String("QAnimationClipData") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QAnimationClipData>()) {
            auto *target = static_cast<Qt3DAnimation::QAnimationClipData *>(value->data());
                *output = QJsonValue(QString(target->name()));
            return true;
        }
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannel
        if (className == QLatin1String("QChannel") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannel>()) {
            auto *target = static_cast<Qt3DAnimation::QChannel *>(value->data());
                *output = QJsonValue(QString(target->name()));
            return true;
        }
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannelComponent
        if (className == QLatin1String("QChannelComponent") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannelComponent>()) {
            auto *target = static_cast<Qt3DAnimation::QChannelComponent *>(value->data());
                *output = QJsonValue(QString(target->name()));
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_11(std::true_type{})) return true;
    auto invoke_signature_12 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("removeChannel(int)")) {
        if (args.size() != 1) { *error = QStringLiteral("removeChannel(int) expects 1 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QAnimationClipData
        if (className == QLatin1String("QAnimationClipData") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QAnimationClipData>()) {
            auto *target = static_cast<Qt3DAnimation::QAnimationClipData *>(value->data());
                target->removeChannel(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_12(std::true_type{})) return true;
    auto invoke_signature_13 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("removeChannelComponent(int)")) {
        if (args.size() != 1) { *error = QStringLiteral("removeChannelComponent(int) expects 1 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannel
        if (className == QLatin1String("QChannel") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannel>()) {
            auto *target = static_cast<Qt3DAnimation::QChannel *>(value->data());
                target->removeChannelComponent(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_13(std::true_type{})) return true;
    auto invoke_signature_14 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("removeKeyFrame(int)")) {
        if (args.size() != 1) { *error = QStringLiteral("removeKeyFrame(int) expects 1 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannelComponent
        if (className == QLatin1String("QChannelComponent") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannelComponent>()) {
            auto *target = static_cast<Qt3DAnimation::QChannelComponent *>(value->data());
                target->removeKeyFrame(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_14(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QVECTOR2D)
    auto invoke_signature_15 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("rightControlPoint()")) {
        if (args.size() != 0) { *error = QStringLiteral("rightControlPoint() expects 0 argument(s)"); return true; }
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame
        if (className == QLatin1String("QKeyFrame") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QKeyFrame>()) {
            auto *target = static_cast<Qt3DAnimation::QKeyFrame *>(value->data());
                const QVariant convertedResult = kry_qt6_direct::storeValue<QVector2D>(target->rightControlPoint());
                if (!convertedResult.isValid()) { *error = QStringLiteral("Qt returned a value Kryndel cannot store"); return true; }
                *output = kry_qt6_direct::toJson(convertedResult);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_15(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QVECTOR2D)
    auto invoke_signature_16 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QVector2D>::Defined && std::is_copy_constructible_v<QVector2D> && std::is_default_constructible_v<QVector2D>) {
    if (signature == QLatin1String("setCoordinates(QVector2D)")) {
        if (args.size() != 1) { *error = QStringLiteral("setCoordinates(QVector2D) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QVector2D>(), error);
            if (!converted0.isValid()) return true;
            const QVector2D arg0 = converted0.value<QVector2D>();
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame
        if (className == QLatin1String("QKeyFrame") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QKeyFrame>()) {
            auto *target = static_cast<Qt3DAnimation::QKeyFrame *>(value->data());
                target->setCoordinates(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_16(std::true_type{})) return true;
#endif
#if defined(KRY_QT6_NATIVE_TYPE_QT3DANIMATION_QKEYFRAME)
    auto invoke_signature_17 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<Qt3DAnimation::QKeyFrame::InterpolationType>::Defined && std::is_copy_constructible_v<Qt3DAnimation::QKeyFrame::InterpolationType> && std::is_default_constructible_v<Qt3DAnimation::QKeyFrame::InterpolationType>) {
    if (signature == QLatin1String("setInterpolationType(Qt3DAnimation::QKeyFrame::InterpolationType)")) {
        if (args.size() != 1) { *error = QStringLiteral("setInterpolationType(Qt3DAnimation::QKeyFrame::InterpolationType) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<Qt3DAnimation::QKeyFrame::InterpolationType>(), error);
            if (!converted0.isValid()) return true;
            Qt3DAnimation::QKeyFrame::InterpolationType arg0 = converted0.value<Qt3DAnimation::QKeyFrame::InterpolationType>();
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame
        if (className == QLatin1String("QKeyFrame") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QKeyFrame>()) {
            auto *target = static_cast<Qt3DAnimation::QKeyFrame *>(value->data());
                target->setInterpolationType(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_17(std::true_type{})) return true;
#endif
    auto invoke_signature_18 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setJointIndex(int)")) {
        if (args.size() != 1) { *error = QStringLiteral("setJointIndex(int) expects 1 argument(s)"); return true; }
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return true; }
            arg0 = static_cast<int>(args.at(0).toDouble());
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannel
        if (className == QLatin1String("QChannel") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannel>()) {
            auto *target = static_cast<Qt3DAnimation::QChannel *>(value->data());
                target->setJointIndex(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_18(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QVECTOR2D)
    auto invoke_signature_19 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QVector2D>::Defined && std::is_copy_constructible_v<QVector2D> && std::is_default_constructible_v<QVector2D>) {
    if (signature == QLatin1String("setLeftControlPoint(QVector2D)")) {
        if (args.size() != 1) { *error = QStringLiteral("setLeftControlPoint(QVector2D) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QVector2D>(), error);
            if (!converted0.isValid()) return true;
            const QVector2D arg0 = converted0.value<QVector2D>();
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame
        if (className == QLatin1String("QKeyFrame") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QKeyFrame>()) {
            auto *target = static_cast<Qt3DAnimation::QKeyFrame *>(value->data());
                target->setLeftControlPoint(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_19(std::true_type{})) return true;
#endif
    auto invoke_signature_20 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value) {
    if (signature == QLatin1String("setName(QString)")) {
        if (args.size() != 1) { *error = QStringLiteral("setName(QString) expects 1 argument(s)"); return true; }
            if (!(args.at(0).isString() || args.at(0).isNull())) { *error = QStringLiteral("argument 0 must be a string or null"); return true; }
            const QString arg0 = args.at(0).isNull() ? QString() : args.at(0).toString();
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QAnimationClipData
        if (className == QLatin1String("QAnimationClipData") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QAnimationClipData>()) {
            auto *target = static_cast<Qt3DAnimation::QAnimationClipData *>(value->data());
                target->setName(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannel
        if (className == QLatin1String("QChannel") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannel>()) {
            auto *target = static_cast<Qt3DAnimation::QChannel *>(value->data());
                target->setName(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannelComponent
        if (className == QLatin1String("QChannelComponent") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QChannelComponent>()) {
            auto *target = static_cast<Qt3DAnimation::QChannelComponent *>(value->data());
                target->setName(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_20(std::true_type{})) return true;
#if defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QVECTOR2D)
    auto invoke_signature_21 = [&](auto enable) -> bool {
        using Enable = decltype(enable);
        if constexpr (Enable::value && QMetaTypeId2<QVector2D>::Defined && std::is_copy_constructible_v<QVector2D> && std::is_default_constructible_v<QVector2D>) {
    if (signature == QLatin1String("setRightControlPoint(QVector2D)")) {
        if (args.size() != 1) { *error = QStringLiteral("setRightControlPoint(QVector2D) expects 1 argument(s)"); return true; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QVector2D>(), error);
            if (!converted0.isValid()) return true;
            const QVector2D arg0 = converted0.value<QVector2D>();
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame
        if (className == QLatin1String("QKeyFrame") && value != nullptr && value->metaType() == QMetaType::fromType<Qt3DAnimation::QKeyFrame>()) {
            auto *target = static_cast<Qt3DAnimation::QKeyFrame *>(value->data());
                target->setRightControlPoint(arg0);
                *output = QJsonValue(QJsonValue::Null);
            return true;
        }
#endif
    }
        }
        return false;
    };
    if (invoke_signature_21(std::true_type{})) return true;
#endif
    return false;
}
QStringList direct_value_types_qt3danimation_0() {
    QStringList result;
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QAnimationClipData
    if (QMetaTypeId2<Qt3DAnimation::QAnimationClipData>::Defined && std::is_copy_constructible_v<Qt3DAnimation::QAnimationClipData>) result.append(QStringLiteral("QAnimationClipData"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannel
    if (QMetaTypeId2<Qt3DAnimation::QChannel>::Defined && std::is_copy_constructible_v<Qt3DAnimation::QChannel>) result.append(QStringLiteral("QChannel"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QChannelComponent
    if (QMetaTypeId2<Qt3DAnimation::QChannelComponent>::Defined && std::is_copy_constructible_v<Qt3DAnimation::QChannelComponent>) result.append(QStringLiteral("QChannelComponent"));
#endif
#ifdef KRY_QT6_NATIVE_METHODS_QT3DANIMATION_QKeyFrame
    if (QMetaTypeId2<Qt3DAnimation::QKeyFrame>::Defined && std::is_copy_constructible_v<Qt3DAnimation::QKeyFrame>) result.append(QStringLiteral("QKeyFrame"));
#endif
    return result;
}
} // namespace kry_qt6_direct
