// Generated by generate_native_methods.py; do not edit by hand.
#include "../qt6_direct.h"
#include <QtCore/QStringList>
#include <cmath>
#include <limits>
#include <type_traits>
#include <utility>

#if __has_include(<QtWidgets/QScrollBar>)
#include <QtWidgets/QScrollBar>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QScrollBar 1
#endif
#if __has_include(<QtWidgets/QSizeGrip>)
#include <QtWidgets/QSizeGrip>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSizeGrip 1
#endif
#if __has_include(<QtWidgets/QSlider>)
#include <QtWidgets/QSlider>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSlider 1
#endif
#if __has_include(<QtWidgets/QSpinBox>)
#include <QtWidgets/QSpinBox>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSpinBox 1
#endif
#if __has_include(<QtWidgets/QSplashScreen>)
#include <QtWidgets/QSplashScreen>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplashScreen 1
#endif
#if __has_include(<QtWidgets/QSplitter>)
#include <QtWidgets/QSplitter>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplitter 1
#endif
#if __has_include(<QtWidgets/QSplitterHandle>)
#include <QtWidgets/QSplitterHandle>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplitterHandle 1
#endif
#if __has_include(<QtWidgets/QStackedLayout>)
#include <QtWidgets/QStackedLayout>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStackedLayout 1
#endif
#if __has_include(<QtWidgets/QStackedWidget>)
#include <QtWidgets/QStackedWidget>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStackedWidget 1
#endif
#if __has_include(<QtWidgets/QStatusBar>)
#include <QtWidgets/QStatusBar>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStatusBar 1
#endif
#if __has_include(<QtWidgets/QStyle>)
#include <QtWidgets/QStyle>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStyle 1
#endif
#if __has_include(<QtWidgets/QStyledItemDelegate>)
#include <QtWidgets/QStyledItemDelegate>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStyledItemDelegate 1
#endif
#if __has_include(<QtWidgets/QSwipeGesture>)
#include <QtWidgets/QSwipeGesture>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSwipeGesture 1
#endif
#if __has_include(<QtWidgets/QSystemTrayIcon>)
#include <QtWidgets/QSystemTrayIcon>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSystemTrayIcon 1
#endif
#if __has_include(<QtWidgets/QTabBar>)
#include <QtWidgets/QTabBar>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTabBar 1
#endif
#if __has_include(<QtWidgets/QTabWidget>)
#include <QtWidgets/QTabWidget>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTabWidget 1
#endif
#if __has_include(<QtWidgets/QTableView>)
#include <QtWidgets/QTableView>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTableView 1
#endif
#if __has_include(<QtWidgets/QTableWidget>)
#include <QtWidgets/QTableWidget>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTableWidget 1
#endif
#if __has_include(<QtWidgets/QTapAndHoldGesture>)
#include <QtWidgets/QTapAndHoldGesture>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTapAndHoldGesture 1
#endif
#if __has_include(<QtWidgets/QTapGesture>)
#include <QtWidgets/QTapGesture>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTapGesture 1
#endif
#if __has_include(<QtWidgets/QTextBrowser>)
#include <QtWidgets/QTextBrowser>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTextBrowser 1
#endif
#if __has_include(<QtWidgets/QTextEdit>)
#include <QtWidgets/QTextEdit>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTextEdit 1
#endif
#if __has_include(<QtWidgets/QTimeEdit>)
#include <QtWidgets/QTimeEdit>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTimeEdit 1
#endif
#if __has_include(<QtWidgets/QToolBar>)
#include <QtWidgets/QToolBar>
#define KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QToolBar 1
#endif
#if __has_include(<QtCore/QObject>)
#include <QtCore/QObject>
#define KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT 1
#endif
#if __has_include(<QtGui/QScreen>)
#include <QtGui/QScreen>
#define KRY_QT6_NATIVE_TYPE_QTGUI_QSCREEN 1
#endif
#if __has_include(<QtWidgets/QLayout>)
#include <QtWidgets/QLayout>
#define KRY_QT6_NATIVE_TYPE_QTWIDGETS_QLAYOUT 1
#endif
#if __has_include(<QtWidgets/QSplitter>)
#include <QtWidgets/QSplitter>
#define KRY_QT6_NATIVE_TYPE_QTWIDGETS_QSPLITTER 1
#endif
#if __has_include(<QtWidgets/QWidget>)
#include <QtWidgets/QWidget>
#define KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET 1
#endif
#include <QtCore/Qt>
#define KRY_QT6_NATIVE_ENUM_QT_ORIENTATION 1
#include <QtCore/Qt>
#define KRY_QT6_NATIVE_ENUM_QT_WINDOWFLAGS 1
#if __has_include(<QtCore/QTime>)
#include <QtCore/QTime>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QTIME 1
#endif
#if __has_include(<QtGui/QIcon>)
#include <QtGui/QIcon>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QICON 1
#endif
#if __has_include(<QtGui/QPixmap>)
#include <QtGui/QPixmap>
#define KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP 1
#endif

namespace {
template <typename T, typename... Args>
QObject *makeQObject(Args &&...args) {
    if constexpr (std::is_abstract_v<T> || !std::is_constructible_v<T, Args...>) return nullptr;
    else return new T(std::forward<Args>(args)...);
}
}

namespace kry_qt6_generated {
bool construct_qtwidgets_3(const QString &moduleName, const QString &className, QObject *parent, const QJsonArray &args, QObject **output, QString *error) {
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QScrollBar") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QScrollBar) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QScrollBar>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QScrollBar") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QScrollBar) && defined(KRY_QT6_NATIVE_ENUM_QT_ORIENTATION) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<Qt::Orientation>::Defined && std::is_copy_constructible_v<Qt::Orientation> && std::is_default_constructible_v<Qt::Orientation>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<Qt::Orientation>(), error);
            if (!converted0.isValid()) return nullptr;
            Qt::Orientation arg0 = converted0.value<Qt::Orientation>();
            QObject *instance = makeQObject<QScrollBar>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSizeGrip") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSizeGrip) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            auto *constructorParent = qobject_cast<QWidget *>(parent);
            if (parent != nullptr && constructorParent == nullptr) { *error = QStringLiteral("parent must be a QWidget object"); return nullptr; }
            QObject *instance = makeQObject<QSizeGrip>(constructorParent);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSlider") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSlider) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QSlider>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSlider") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSlider) && defined(KRY_QT6_NATIVE_ENUM_QT_ORIENTATION) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<Qt::Orientation>::Defined && std::is_copy_constructible_v<Qt::Orientation> && std::is_default_constructible_v<Qt::Orientation>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<Qt::Orientation>(), error);
            if (!converted0.isValid()) return nullptr;
            Qt::Orientation arg0 = converted0.value<Qt::Orientation>();
            QObject *instance = makeQObject<QSlider>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSpinBox") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSpinBox) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QSpinBox>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSplashScreen") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplashScreen) && defined(KRY_QT6_NATIVE_ENUM_QT_WINDOWFLAGS) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QSplashScreen>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSplashScreen") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplashScreen) && defined(KRY_QT6_NATIVE_ENUM_QT_WINDOWFLAGS) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QPixmap>::Defined && std::is_copy_constructible_v<QPixmap> && std::is_default_constructible_v<QPixmap>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QPixmap>(), error);
            if (!converted0.isValid()) return nullptr;
            const QPixmap arg0 = converted0.value<QPixmap>();
            QObject *instance = makeQObject<QSplashScreen>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplashScreen) && defined(KRY_QT6_NATIVE_ENUM_QT_WINDOWFLAGS) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QSCREEN) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return nullptr; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QScreen*>(), error);
            if (!converted0.isValid()) return nullptr;
            QScreen* const arg0 = converted0.value<QScreen*>();
            QObject *instance = makeQObject<QSplashScreen>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSplashScreen") && args.size() == 2) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplashScreen) && defined(KRY_QT6_NATIVE_ENUM_QT_WINDOWFLAGS) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QPixmap>::Defined && std::is_copy_constructible_v<QPixmap> && std::is_default_constructible_v<QPixmap> && QMetaTypeId2<Qt::WindowFlags>::Defined && std::is_copy_constructible_v<Qt::WindowFlags> && std::is_default_constructible_v<Qt::WindowFlags>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QPixmap>(), error);
            if (!converted0.isValid()) return nullptr;
            const QPixmap arg0 = converted0.value<QPixmap>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<Qt::WindowFlags>(), error);
            if (!converted1.isValid()) return nullptr;
            Qt::WindowFlags arg1 = converted1.value<Qt::WindowFlags>();
            QObject *instance = makeQObject<QSplashScreen>(arg0, arg1);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplashScreen) && defined(KRY_QT6_NATIVE_ENUM_QT_WINDOWFLAGS) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QSCREEN) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QPixmap>::Defined && std::is_copy_constructible_v<QPixmap> && std::is_default_constructible_v<QPixmap>) {
            QString *error = &candidateError;
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return nullptr; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QScreen*>(), error);
            if (!converted0.isValid()) return nullptr;
            QScreen* const arg0 = converted0.value<QScreen*>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QPixmap>(), error);
            if (!converted1.isValid()) return nullptr;
            const QPixmap arg1 = converted1.value<QPixmap>();
            QObject *instance = makeQObject<QSplashScreen>(arg0, arg1);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSplashScreen") && args.size() == 3) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplashScreen) && defined(KRY_QT6_NATIVE_ENUM_QT_WINDOWFLAGS) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QSCREEN) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QPixmap>::Defined && std::is_copy_constructible_v<QPixmap> && std::is_default_constructible_v<QPixmap> && QMetaTypeId2<Qt::WindowFlags>::Defined && std::is_copy_constructible_v<Qt::WindowFlags> && std::is_default_constructible_v<Qt::WindowFlags>) {
            QString *error = &candidateError;
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return nullptr; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QScreen*>(), error);
            if (!converted0.isValid()) return nullptr;
            QScreen* const arg0 = converted0.value<QScreen*>();
            const QVariant converted1 = kry_qt6_direct::fromJson(args.at(1), QMetaType::fromType<QPixmap>(), error);
            if (!converted1.isValid()) return nullptr;
            const QPixmap arg1 = converted1.value<QPixmap>();
            const QVariant converted2 = kry_qt6_direct::fromJson(args.at(2), QMetaType::fromType<Qt::WindowFlags>(), error);
            if (!converted2.isValid()) return nullptr;
            Qt::WindowFlags arg2 = converted2.value<Qt::WindowFlags>();
            QObject *instance = makeQObject<QSplashScreen>(arg0, arg1, arg2);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSplitter") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplitter) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QSplitter>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSplitter") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplitter) && defined(KRY_QT6_NATIVE_ENUM_QT_ORIENTATION) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<Qt::Orientation>::Defined && std::is_copy_constructible_v<Qt::Orientation> && std::is_default_constructible_v<Qt::Orientation>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<Qt::Orientation>(), error);
            if (!converted0.isValid()) return nullptr;
            Qt::Orientation arg0 = converted0.value<Qt::Orientation>();
            QObject *instance = makeQObject<QSplitter>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSplitterHandle") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplitterHandle) && defined(KRY_QT6_NATIVE_ENUM_QT_ORIENTATION) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QSPLITTER)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<Qt::Orientation>::Defined && std::is_copy_constructible_v<Qt::Orientation> && std::is_default_constructible_v<Qt::Orientation>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<Qt::Orientation>(), error);
            if (!converted0.isValid()) return nullptr;
            Qt::Orientation arg0 = converted0.value<Qt::Orientation>();
            auto *constructorParent = qobject_cast<QSplitter *>(parent);
            if (parent != nullptr && constructorParent == nullptr) { *error = QStringLiteral("parent must be a QSplitter object"); return nullptr; }
            QObject *instance = makeQObject<QSplitterHandle>(arg0, constructorParent);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QStackedLayout") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStackedLayout)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QStackedLayout>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStackedLayout) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            auto *constructorParent = qobject_cast<QWidget *>(parent);
            if (parent != nullptr && constructorParent == nullptr) { *error = QStringLiteral("parent must be a QWidget object"); return nullptr; }
            QObject *instance = makeQObject<QStackedLayout>(constructorParent);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QStackedLayout") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStackedLayout) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QLAYOUT)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (args.at(0).isNull()) { *error = QStringLiteral("argument 0 cannot be null"); return nullptr; }
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QLayout*>(), error);
            if (!converted0.isValid()) return nullptr;
            QLayout* const arg0 = converted0.value<QLayout*>();
            QObject *instance = makeQObject<QStackedLayout>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QStackedWidget") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStackedWidget) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QStackedWidget>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QStatusBar") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStatusBar) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QStatusBar>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QStyle") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStyle)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QStyle>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QStyledItemDelegate") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStyledItemDelegate) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QStyledItemDelegate>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSwipeGesture") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSwipeGesture) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QSwipeGesture>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSystemTrayIcon") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSystemTrayIcon) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QSystemTrayIcon>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QSystemTrayIcon") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSystemTrayIcon) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QICON)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QIcon>::Defined && std::is_copy_constructible_v<QIcon> && std::is_default_constructible_v<QIcon>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QIcon>(), error);
            if (!converted0.isValid()) return nullptr;
            const QIcon arg0 = converted0.value<QIcon>();
            QObject *instance = makeQObject<QSystemTrayIcon>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTabBar") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTabBar) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QTabBar>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTabWidget") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTabWidget) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QTabWidget>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTableView") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTableView) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QTableView>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTableWidget") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTableWidget) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QTableWidget>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTableWidget") && args.size() == 2) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTableWidget) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            int arg0 = 0;
            if (!args.at(0).isDouble() || !std::isfinite(args.at(0).toDouble()) || std::floor(args.at(0).toDouble()) != args.at(0).toDouble() || args.at(0).toDouble() < std::numeric_limits<int>::min() || args.at(0).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 0 must be a 32-bit integer"); return nullptr; }
            arg0 = static_cast<int>(args.at(0).toDouble());
            int arg1 = 0;
            if (!args.at(1).isDouble() || !std::isfinite(args.at(1).toDouble()) || std::floor(args.at(1).toDouble()) != args.at(1).toDouble() || args.at(1).toDouble() < std::numeric_limits<int>::min() || args.at(1).toDouble() > std::numeric_limits<int>::max()) { *error = QStringLiteral("argument 1 must be a 32-bit integer"); return nullptr; }
            arg1 = static_cast<int>(args.at(1).toDouble());
            QObject *instance = makeQObject<QTableWidget>(arg0, arg1);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTapAndHoldGesture") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTapAndHoldGesture) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QTapAndHoldGesture>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTapGesture") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTapGesture) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QTapGesture>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTextBrowser") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTextBrowser) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QTextBrowser>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTextEdit") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTextEdit) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QTextEdit>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTextEdit") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTextEdit) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return nullptr; }
            const QString arg0 = args.at(0).toString();
            QObject *instance = makeQObject<QTextEdit>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTimeEdit") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTimeEdit) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QTimeEdit>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QTimeEdit") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTimeEdit) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QTIME)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value && QMetaTypeId2<QTime>::Defined && std::is_copy_constructible_v<QTime> && std::is_default_constructible_v<QTime>) {
            QString *error = &candidateError;
            const QVariant converted0 = kry_qt6_direct::fromJson(args.at(0), QMetaType::fromType<QTime>(), error);
            if (!converted0.isValid()) return nullptr;
            const QTime arg0 = converted0.value<QTime>();
            QObject *instance = makeQObject<QTimeEdit>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QToolBar") && args.size() == 0) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QToolBar) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            QObject *instance = makeQObject<QToolBar>();
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    if ((moduleName.isEmpty() || moduleName == QLatin1String("QtWidgets")) &&
        className == QLatin1String("QToolBar") && args.size() == 1) {
        QString lastCandidateError;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QToolBar) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
        {
        QString candidateError;
        auto construct_candidate = [&](auto enable) -> QObject * {
            using Enable = decltype(enable);
            if constexpr (Enable::value) {
            QString *error = &candidateError;
            if (!(args.at(0).isString())) { *error = QStringLiteral("argument 0 must be a string"); return nullptr; }
            const QString arg0 = args.at(0).toString();
            QObject *instance = makeQObject<QToolBar>(arg0);
            if (instance == nullptr) return nullptr;
            QObject *attached = kry_qt6_direct::adopt(instance, parent, error);
            if (attached == nullptr) { delete instance; return nullptr; }
            return attached;
            }
            return nullptr;
        };
        QObject *created = construct_candidate(std::true_type{});
        if (created != nullptr) { *output = created; return true; }
        if (!candidateError.isEmpty()) lastCandidateError = candidateError;
        }
#endif
        if (!lastCandidateError.isEmpty()) *error = lastCandidateError;
        return true;
    }
    return false;
}
QStringList constructor_classes_qtwidgets_3() {
    QStringList result;
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QScrollBar) && defined(KRY_QT6_NATIVE_ENUM_QT_ORIENTATION) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QScrollBar> && (std::is_constructible_v<QScrollBar, QWidget*> || std::is_constructible_v<QScrollBar, Qt::Orientation, QWidget*>)) result.append(QStringLiteral("QScrollBar"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSizeGrip) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QSizeGrip> && (std::is_constructible_v<QSizeGrip, QWidget*>)) result.append(QStringLiteral("QSizeGrip"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSlider) && defined(KRY_QT6_NATIVE_ENUM_QT_ORIENTATION) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QSlider> && (std::is_constructible_v<QSlider, QWidget*> || std::is_constructible_v<QSlider, Qt::Orientation, QWidget*>)) result.append(QStringLiteral("QSlider"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSpinBox) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QSpinBox> && (std::is_constructible_v<QSpinBox, QWidget*>)) result.append(QStringLiteral("QSpinBox"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplashScreen) && defined(KRY_QT6_NATIVE_ENUM_QT_WINDOWFLAGS) && defined(KRY_QT6_NATIVE_TYPE_QTGUI_QSCREEN) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QPIXMAP)
    if (!std::is_abstract_v<QSplashScreen> && (std::is_constructible_v<QSplashScreen, QPixmap, Qt::WindowFlags> || std::is_constructible_v<QSplashScreen, QScreen*, QPixmap, Qt::WindowFlags>)) result.append(QStringLiteral("QSplashScreen"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplitter) && defined(KRY_QT6_NATIVE_ENUM_QT_ORIENTATION) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QSplitter> && (std::is_constructible_v<QSplitter, QWidget*> || std::is_constructible_v<QSplitter, Qt::Orientation, QWidget*>)) result.append(QStringLiteral("QSplitter"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSplitterHandle) && defined(KRY_QT6_NATIVE_ENUM_QT_ORIENTATION) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QSPLITTER)
    if (!std::is_abstract_v<QSplitterHandle> && (std::is_constructible_v<QSplitterHandle, Qt::Orientation, QSplitter*>)) result.append(QStringLiteral("QSplitterHandle"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStackedLayout) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QLAYOUT) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QStackedLayout> && (std::is_constructible_v<QStackedLayout> || std::is_constructible_v<QStackedLayout, QWidget*> || std::is_constructible_v<QStackedLayout, QLayout*>)) result.append(QStringLiteral("QStackedLayout"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStackedWidget) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QStackedWidget> && (std::is_constructible_v<QStackedWidget, QWidget*>)) result.append(QStringLiteral("QStackedWidget"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStatusBar) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QStatusBar> && (std::is_constructible_v<QStatusBar, QWidget*>)) result.append(QStringLiteral("QStatusBar"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStyle)
    if (!std::is_abstract_v<QStyle> && (std::is_constructible_v<QStyle>)) result.append(QStringLiteral("QStyle"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QStyledItemDelegate) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
    if (!std::is_abstract_v<QStyledItemDelegate> && (std::is_constructible_v<QStyledItemDelegate, QObject*>)) result.append(QStringLiteral("QStyledItemDelegate"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSwipeGesture) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
    if (!std::is_abstract_v<QSwipeGesture> && (std::is_constructible_v<QSwipeGesture, QObject*>)) result.append(QStringLiteral("QSwipeGesture"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QSystemTrayIcon) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTGUI_QICON)
    if (!std::is_abstract_v<QSystemTrayIcon> && (std::is_constructible_v<QSystemTrayIcon, QObject*> || std::is_constructible_v<QSystemTrayIcon, QIcon, QObject*>)) result.append(QStringLiteral("QSystemTrayIcon"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTabBar) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QTabBar> && (std::is_constructible_v<QTabBar, QWidget*>)) result.append(QStringLiteral("QTabBar"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTabWidget) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QTabWidget> && (std::is_constructible_v<QTabWidget, QWidget*>)) result.append(QStringLiteral("QTabWidget"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTableView) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QTableView> && (std::is_constructible_v<QTableView, QWidget*>)) result.append(QStringLiteral("QTableView"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTableWidget) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QTableWidget> && (std::is_constructible_v<QTableWidget, QWidget*> || std::is_constructible_v<QTableWidget, int, int, QWidget*>)) result.append(QStringLiteral("QTableWidget"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTapAndHoldGesture) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
    if (!std::is_abstract_v<QTapAndHoldGesture> && (std::is_constructible_v<QTapAndHoldGesture, QObject*>)) result.append(QStringLiteral("QTapAndHoldGesture"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTapGesture) && defined(KRY_QT6_NATIVE_TYPE_QTCORE_QOBJECT)
    if (!std::is_abstract_v<QTapGesture> && (std::is_constructible_v<QTapGesture, QObject*>)) result.append(QStringLiteral("QTapGesture"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTextBrowser) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QTextBrowser> && (std::is_constructible_v<QTextBrowser, QWidget*>)) result.append(QStringLiteral("QTextBrowser"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTextEdit) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QTextEdit> && (std::is_constructible_v<QTextEdit, QWidget*> || std::is_constructible_v<QTextEdit, QString, QWidget*>)) result.append(QStringLiteral("QTextEdit"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QTimeEdit) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET) && defined(KRY_QT6_NATIVE_VALUE_TYPE_QTCORE_QTIME)
    if (!std::is_abstract_v<QTimeEdit> && (std::is_constructible_v<QTimeEdit, QWidget*> || std::is_constructible_v<QTimeEdit, QTime, QWidget*>)) result.append(QStringLiteral("QTimeEdit"));
#endif
#if defined(KRY_QT6_NATIVE_CONSTRUCTORS_QTWIDGETS_QToolBar) && defined(KRY_QT6_NATIVE_TYPE_QTWIDGETS_QWIDGET)
    if (!std::is_abstract_v<QToolBar> && (std::is_constructible_v<QToolBar, QString, QWidget*> || std::is_constructible_v<QToolBar, QWidget*>)) result.append(QStringLiteral("QToolBar"));
#endif
    return result;
}
} // namespace kry_qt6_generated
