package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/format"
	"os"
	"sort"
	"strconv"
)

func main() {
	cAOT, err := stringCases("codegen.go", "builtinCall")
	if err != nil {
		fail(err)
	}
	directELF, err := stringCases("machine_dynamic.go", "emitExpr")
	if err != nil {
		fail(err)
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&out, "package kry")
	fmt.Fprintln(&out, "var generatedCAOTBuiltinCases = map[string]struct{}{")
	writeCases(&out, cAOT)
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out, "var generatedDirectELFBuiltinCases = map[string]struct{}{")
	writeCases(&out, directELF)
	fmt.Fprintln(&out, "}")
	source, err := format.Source(out.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("native_features_gen.go", source, 0o644); err != nil {
		fail(err)
	}
}

func stringCases(filename, functionName string) ([]string, error) {
	f, err := parser.ParseFile(token.NewFileSet(), filename, nil, parser.AllErrors)
	if err != nil {
		return nil, err
	}
	var function *ast.FuncDecl
	for _, decl := range f.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok && fn.Name.Name == functionName {
			function = fn
			break
		}
	}
	if function == nil {
		return nil, fmt.Errorf("function %s not found in %s", functionName, filename)
	}
	seen := map[string]bool{}
	ast.Inspect(function.Body, func(node ast.Node) bool {
		sw, ok := node.(*ast.SwitchStmt)
		if !ok {
			return true
		}
		tag, ok := sw.Tag.(*ast.SelectorExpr)
		if !ok || tag.Sel.Name != "Name" {
			return true
		}
		for _, raw := range sw.Body.List {
			clause, ok := raw.(*ast.CaseClause)
			if !ok {
				continue
			}
			for _, expr := range clause.List {
				literal, ok := expr.(*ast.BasicLit)
				if !ok || literal.Kind != token.STRING {
					continue
				}
				name, err := strconv.Unquote(literal.Value)
				if err == nil {
					seen[name] = true
				}
			}
		}
		return true
	})
	values := make([]string, 0, len(seen))
	for value := range seen {
		values = append(values, value)
	}
	sort.Strings(values)
	return values, nil
}

func writeCases(out *bytes.Buffer, values []string) {
	for _, value := range values {
		fmt.Fprintf(out, "\t%q: {},\n", value)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "kry-capgen:", err)
	os.Exit(1)
}
